### ISSUE TITLE
ar_bridge:start_link/1 starts unlinked

### ISSUE THREAD

**Issue by martin-torhage** [ArweaveTeam/arweave#102]
`ar_bridge:start_link/1` doesn't link to the spawned process, so the supervisor supposed to supervise it in `ar:start/1` doesn't work.

**Comment by Raphexion** [comment]
Why don't we use normal gen_server behaviour in ar_bridge? It seems like there is a little erlang magic (erlang:apply) and a spawns.

**Comment by ldmberman** [comment]
Reworked [here](https://github.com/ArweaveTeam/arweave/commit/f8f4771b465d09e92a59096344aba31b2ab7cff6).
