### ISSUE TITLE
Blocks get rejected based on block height prematurely without checking cumulated diff

### ISSUE THREAD

**Issue by martin-torhage** [ArweaveTeam/arweave#103]
When receiving a block in `ar_http_iface_server`, `post_block/2` rejects the block if its height is not higher than the current block height. This is a left-over from before we had cumulative diff. Instead of filtering on block height like this, we should let `is_fork_preferable/3` in `ar_node_worker` decide.

**Comment by ldmberman** [comment]
Has been addressed some time ago.
