### ISSUE TITLE
Support multiple transactions per wallet per block

### ISSUE THREAD

**Issue by ldmberman** [ArweaveTeam/arweave#105]
Mempool should accept multiple transactions per wallet if they are ordered (i.e. they reference each other, and the first transaction references the last transaction of the wallet), their total value does not exceed the wallet balance, and each of them is valid when applied on top of the previous one.

Possibly, accept out of order transactions but kick them out after a short timeout. This way, transactions can survive out of order gossip but bad actors can then abuse mempool by posting transactions that won't be mined. Although the amount is limited by the wallet balance, one can constantly keep a certain portion of miners' memory filled up.

Optionally, accept transactions without a predetermined order. Then, out of order gossip does not introduce issues, and the mempool cannot be abused as described above.

- [x] Define `FORK_1_7` and make sure the new validation rules only apply above this height
- [x] Validate incoming transactions against the floating wallet list
- [x] Update the floating wallet list without waiting for the network propagation delay
- [x] Update the miner so that multiple txs per wallet are possibly chosen for the new block
- [x] Update`ar_node_worker:integrate_block_from_miner` so that the floating wallet list possibly preserves multiple txs per wallet
- [x] Update `ar_node_utils:integrate_new_block` so that the floating wallet list possibly preserves multiple txs per wallet

**Comment by martin-torhage** [comment]
Since this is a hard fork, we need to define the fork height (like `FORK_1_6`) and keep the current behaviour if we haven't passed the fork height yet.

I haven't looked through the current code, but it sounds like `ar_node_worker:encounter_new_tx` is the place for dealing with new transactions and `ar_http_iface_server` does not.

**Comment by ldmberman** [comment]
The feature branch - `feature/multiple-txs-per-wallet-per-block`.

**Comment by JustMaier** [comment]
Got an estimated release date for this? This is kind of a showstopper for serious arweave integration.

**Comment by ldmberman** [comment]
@JustMaier we expect to release it some time in the next few months.

**Comment by JustMaier** [comment]
@ldmberman is there a workaround for this in the meantime?

**Comment by ldmberman** [comment]
If you set up a node locally for development, you could try to use this branch to test the integration. On the mainnet perhaps it would help if you use multiple wallets?

**Comment by JustMaier** [comment]
Any way we can help with development? Being limited to 1 tx per wallet per block severely limits the usability of the Arweave. The idea of having a database that can only take a write request from a user once every 3-5 minutes is pretty funny🤣

**Comment by ldmberman** [comment]
Yeah I agree it sucks. We have had it on our radars for quite some time already, even the initial implementation has been sitting there for a while but other important things were popping up here and there so it was getting postponed. We are trying hard to think about how to arrange everything and find ways to ship it faster.

**Comment by martin-torhage** [comment]
@JustMaier One work-around is to use multiple wallets.

**Comment by ldmberman** [comment]
[The feature has been released in N.1.8.0.0](https://github.com/ArweaveTeam/arweave/releases/tag/N.1.8.0.0).
