### ISSUE TITLE
Miner doesn't reconnect after losing connection

### ISSUE THREAD

**Issue by arthurk** [ArweaveTeam/arweave#117]
There's a problem that happens when the miner is running and the internet connection is lost. The log is full of errors similar to: `Thursday, 13:22:55: WARNING: No foreign blocks received from network. Please check your internet connection.`.

The internet connection was fine but I had to restart the miner in order to get it working again. It would be nicer if the miner automatically tries to reconnect.

**Comment by ldmberman** [comment]
Also, note that your node does not establish long-lived connections. When it mines a block, it establishes connections with the peers to gossip the block; other peers may in turn establish connections to the node to inform it about new blocks.

**Comment by arthurk** [comment]
@martin-torhage i cannot check it anymore since I've restarted the node and it now works fine, but I'm very sure it was over 50 blocks behind

**Comment by ldmberman** [comment]
We've updated the [mining guide](https://docs.arweave.org/info/mining/mining-guide#make-sure-your-node-is-accessible-on-the-internet) with some details on how to troubleshoot this situation. Feel free to reopen if you suspect something else is wrong.
