### ISSUE TITLE
Arweave build failure

### ISSUE THREAD

**Issue by syves** [ArweaveTeam/arweave#13]
I believe the Arweave dockerfile build is failing. Any Erlang heroes out there who could help me understand this?

cd lib/jiffy && ./rebar compile && cd ../.. && mv lib/jiffy/priv ./
{"init terminating in do_boot",{load_failed,[erl_lint,ets,lists,gen_server,erl_eval,gen,filename,erl_parse,proc_lib,gen_event,supervisor]}}
init terminating in do_boot ({load_failed,[erl_lint,ets,lists,gen_server,erl_eval,gen,filename,erl_parse,proc_lib,gen_event,supervisor]})

Crash dump is being written to: erl_crash.dump...done
make: *** [Makefile:39: all] Error 1
ERROR: Service 'arweave' failed to build: The command '/bin/sh -c make all' returned a non-zero code: 2

**Comment by samcamwilliams** [comment]
Hi @syves -- what version are you using, please?

Thanks!
Sam

**Comment by samcamwilliams** [comment]
Hi @syves,

We have made some significant improvements to the docker build system in #16, and have tested it in a number of situations.

Please can you confirm whether you are still experiencing the issue? If not, as we haven't heard from you, we will close the issue.

All the best,
Sam
