### ISSUE TITLE
GraphQL transactions query performance degrades significantly when retrieving tags.

### ISSUE THREAD

**Issue by aokisok** [ArweaveTeam/arweave#176]
When using GraphQL endpoint and the `transactions` query to retrieving any tag values, response times rapidly increase by a minimum of 10x, compared to just retrieving the Id. 

This very quickly leads to 502 Gateway timeout errors. 

This query, which should return about 61 rows, leads to a timeout.  

```
{
    transactions(tags: [{ name: "from", value: "uhE-QeYS8i4pmUtnxQyHD7dzXFNaJ9oMK-IM-QPNY6M" }]) {
      id,
      tagValue(tagName: "from")
    }
}
```

Note this happens with any tagValue, whether it was used in the filter or not. 

A more comprehensive repro is attached, it tests a few combinations of filters/tag queries/row sizes and times them. 

Unzip and `npm i && npx ts-node tags-timing-test.ts`  

The single 'transaction' query does not seem to be affected.

[tags-timing-test.zip](https://github.com/ArweaveTeam/arweave/files/3693878/tags-timing-test.zip)

**Comment by aokisok** [comment]
I updated the original zip file with the repro to be a bit cleaner code, and have it compare against doing the same queries with ArQL. 

Sample output (times are in seconds) 

```
--  ArQL with concurrent requests
Got 11 IDs in 0.807
Got all tags for 11 in 0.155
Total time 0.9620000000000001

--  GraphQL with concurrent requests
Got 11 IDs in 0.744
Got all tags for 11 in 2.878
Total time 3.622

--  Standard GraphQL (one request) - All Tags
Got 11 IDs & all tags in 17.155

--  Standard GraphQL (one request) - 1 Tag
Got 11 IDs & 1 tag in 14.478
```

The timings are very consistent across runs. The  'concurrent request`' tests first do one query to get the list of IDs only, then concurrent requests to get the data for each ID. 

This not an *exact* comparison between the queries, as the GraphQl endpoint returns a few more tags (non-user defined tags such as `reward`, `from`, etc ) but the very last test in the list, is doing this query: 

```
{
  transactions(tags: [{ name: "PermaPasteType", value: "P" }]) {
    id,
    tagValue(tagName:"PermaPasteType")
  }
}
```

IE, it's filtering on one user defined tag and returning 1 user defined tag, and it takes 14 seconds to get 11 rows back! Compared to the first test where we can get the same 11 rows and all user-defined tags in under a second by doing 1+11 requests with ArQl (and in about 3.5 seconds with 1+11 GQL queries) 

I'm sure you are looking into this and its not a big deal for me, but I improved the repro tests last week and just hadn't got around to coming back to this issue yet, so just putting this info here for yourselves and others.

Personally, I'd prefer to see some more simple improvements just added to the ArQL / tags endpoints :) Its a perfectly fine interface for querying IMO, I have a bunch more thoughts on that but I'll leave it for another time.

**Comment by arweave-kyle** [comment]
Hey @aokisok I think this is quite a simple test so it misses a bunch of detail as it's an absolute best-case test for the original ArQL style queries. With GraphQL you can define more complex queries with nested queries without any additional http requests, like this for example

```graphql
query {
  transactions(tags: [{name: "App-Name", value: "querweave"}, {name: "Type", value: "question"}]) {
    id
    answers: linkedFromTransactions(byForeignTag: "Question-Tx", tags: [{name: "App-Name", value: "querweave"}, {name: "Type", value: "answer"}]) {
      id
    }
  }
}

```

It gets all the transaction ids from the app `querweave`, (community built Quora-style QA on Arweave), and the response comes back with a result set with questions and answers nicely grouped together, like this...

```json
{
  "data": {
    "transactions": [
      {
        "id": "kGRRosnxp_PGa2bFsqWXYoi_CLbOsLzfJvUlanZ2lj4",
        "answers": [
          {
            "id": "ToUZRgnKzJMC12OeCKjTgSXZrB6-3NJBFuxi4lO3ihY"
          }
        ]
      },
      {
        "id": "1K8I9nG-rlbBaQ2-KQA2r9APq2VVWoAv7YAJW7E7e4Q",
        "answers": [
          {
            "id": "p6ZEOiLKOpF5e3wcTcftnxkpn4Ky1y_xaFQFVmjenHQ"
          }
        ]
      },
      {
        "id": "627evwQcyetglzlxigkq_6zePtKU9I9dNe35BbuVcpo",
        "answers": [
          {
            "id": "r7aLtGnuNEneQg8tqTiFZv71tXa3WEtdJYZNF_b_q18"
          },
          {
            "id": "OuTkrHCMK6CckNonAHNzRleh0CiOaSg4dpHbptN1pMM"
          },
          {
            "id": "5qbwSMZccw2g6xw_F_CQ7q8I7aYoCGI5snht722ofGc"
          },
          {
            "id": "MaFKayjEGv4xzzy2gIbTkjeRYBhl2x0ken5AcE6buEk"
          },
...
```

With the old ArQL syntax something like this isn't possible without dozens of round trip HTTP requests. One request to get the questions, and then for every question in the response, we need to make an additional full ArQL http request to get the answers for it, so that doesn't scale well here at all.

This GraphQL query for example with the updated database returns in ~50ms or so, with original ArQL syntax the http overhead of going back and forth makes it slower overall (and wastes bandwidth/resources along the way).

We expect to see more complex sets of connected data over time, so we think GraphQL gives us a good base to work up from.

**Comment by aokisok** [comment]
Results of the same test with new backend, now its much faster, retrieving all tags for 13txs completes in a bout 100-200ms.  👍👍 🎉 

Closing this issue

```
--  ArQL with concurrent requests
Got 88 IDs in 0.693
Got all tags for 88 in 1.843
Total time 2.536

--  GraphQL with concurrent requests
Got 13 IDs in 0.241
Got all tags for 13 in 0.244
Total time 0.485

--  Standard GraphQL (one request) - All Tags
Got 13 IDs & all tags in 0.196

--  Standard GraphQL (one request) - 1 Tag
Got 13 IDs & 1 tag in 0.275
```
