### ISSUE TITLE
How to post and load images

### ISSUE THREAD

**Issue by glowkeeper** [ArweaveTeam/arweave#193]
This is a cross-post from `hooverd`, here: https://github.com/samcamwilliams/hooverd/issues/2

Please forgive me if that's out of order, but I'm not sure if my issue is with `hooverd` or `arweave` in general...

So I'm using `hooverd` to post images to _arweave_. Something like so:

```
curl -s -k -X POST -F "image=@/tmp/fileName.jpg" http://localhost:1908/raw
```
Which seems to work, as I get a transaction hash. Indeed if I load that hash into a browser, like so:

````
http://arweave.net/P0PKdcucz30ceirUrxASliAMqaUbOBnzxyWQe5YikwY
````

I see a whole load of binary data. But I can't just load the image. I'm guessing I could probably grab that URL with `curl` and edit that binary data to turn it back into the source image, but am I doing something wrong?

As an aside, I have the Chrome _arweave_ extension, and although it shows my correct wallet balance, it doesn't seem to show any of the `hooverd` stuff.

**Comment by samcamwilliams** [comment]
Hey @glowkeeper ,

You will need to provide the right `Content-Type` tag in order for the data to render appropriately in the browser!

Sam

**Comment by glowkeeper** [comment]
Hi @samcamwilliams - if you go to that URL (http://arweave.net/P0PKdcucz30ceirUrxASliAMqaUbOBnzxyWQe5YikwY), it seems to contain the Content-Type...

**Comment by ldmberman** [comment]
@glowkeeper hi, the default content type is `text/html`. You need to assign the `Content-Type` tag to your transaction to change that - in this case it would be `image/jpg`.

**Comment by glowkeeper** [comment]
@ldmberman - thanks!

For the application for which I was trying (and failing) to load images, I am now doing things differently. Rather than attempting to push individual images up to Arweave, I now base64 encode the images and embed them in a single web page. That works really nicely. Furthermore, it's much more efficient and significantly cheaper :) So I've 'evolved' from the initial problem ;)

**Comment by samcamwilliams** [comment]
Hey @glowkeeper ,

Just checked out your other research projects -- they look awesome! Would love to help you get Provenator and ReportAid onto Arweave. How was your experience with Dat?

**Comment by glowkeeper** [comment]
Hi @samcamwilliams!

> Just checked out your other research projects -- they look awesome! 

Thanks!

>  How was your experience with Dat?

As soon I found [homebase](https://github.com/beakerbrowser/homebase) and pinning my dats became trivial, I grew to like it ;) In particular, I like that it's free and that I can upgrade content and keep the same hash - that's awesome. What I dislike is that people need to install browser plugins to load dats, and not everyone is willing to do that...

> Would love to help you get Provenator and ReportAid onto Arweave.

Yup - that'd be cool! Besides, I was aware I should do that ;) 

It shouldn't be too hard, right? [hooverd](https://github.com/samcamwilliams/hooverd) took away much of the pain of deploying to arweave, so I'm no expert ;),  but there's just a `bundle.js`, an `index.html` and a `favicon.png`, so I'm imagining packaging those, somehow (ps. the _Read more about packaging_ link at https://docs.arweave.org/developers/tools/arweave-deploy is broken)?

Thanks again...

Steve

**Comment by glowkeeper** [comment]
Actually, I just jumped onto your Discord Server, and spotted your gitcoin bounty: https://gitcoin.co/issue/ArweaveTeam/Bounties/1/2929? Am I able to apply for that?

It'd be nice to push ReportAid there, first, I think - the UX could do with some polish, probably (I'm not a UX designer), but the UN's UK development team, [Development Initiatives](http://devinit.org/), are currently looking at that, so it might be a good fit...

**Comment by glowkeeper** [comment]
Oooo - https://gitcoin.co/issue/ArweaveTeam/Bounties/17/3699 - I'm incredibly busy, but I may just try and make space for that ;)

**Comment by glowkeeper** [comment]
And I just found this: https://github.com/DustinJackson/html-webpack-inline-source-plugin, which should make pushing my apps to Arweave, using `hooverd`, an absolute breeze ;)

**Comment by ldmberman** [comment]
@glowkeeper feel free to reopen if you still have questions
