### ISSUE TITLE
libtinfo.so.5: cannot open shared object file

### ISSUE THREAD

**Issue by pheelLikeWater** [ArweaveTeam/arweave#223]
Hello,

when trying to start the miner, im always getting the above error message.
Is the current version not compatible with newer Ubuntu versions?

Best regards

**Comment by vkatsuba** [comment]
Hi @pheelLikeWater ,
Try 
```sh
$ locate libtinfo.so
$ sudo ln -s /usr/lib/libtinfo.so /usr/lib/libtinfo.so.5
```
Note:
```
Starting from ncurses 5.0 main ncurses library was splitted into two smaller:
libncurses and libtinfo (with terminal functions only) so you should
simply install ncurses 5 package.
```

Regards,
--V

**Comment by ldmberman** [comment]
Hey @pheelLikeWater, feel free to reopen if you still experience this issue

**Comment by megu01s** [comment]
Hello, 
I'm having some trouble to run arweave too... As  @vkatsuba  mentionned, I installed libtinfo and created the symlink to make sure this file exist. I'm quite a newbie on Linux.

But I'm still getting the same error after doing it all : 
/home/megu/arweave/bin/arweave: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory

This is what I get when I use locate libtinfo.so : 
megu@megu01s:~/arweave$ locate libtinfo.so
/snap/core/11081/lib/x86_64-linux-gnu/libtinfo.so.5
/snap/core/11081/lib/x86_64-linux-gnu/libtinfo.so.5.9
/snap/core18/1997/lib/x86_64-linux-gnu/libtinfo.so.5
/snap/core18/1997/lib/x86_64-linux-gnu/libtinfo.so.5.9
/snap/core18/2066/lib/x86_64-linux-gnu/libtinfo.so.5
/snap/core18/2066/lib/x86_64-linux-gnu/libtinfo.so.5.9
/snap/core20/1026/usr/lib/x86_64-linux-gnu/libtinfo.so.6
/snap/core20/1026/usr/lib/x86_64-linux-gnu/libtinfo.so.6.2
/snap/core20/975/usr/lib/x86_64-linux-gnu/libtinfo.so.6
/snap/core20/975/usr/lib/x86_64-linux-gnu/libtinfo.so.6.2
/usr/lib/x86_64-linux-gnu/libtinfo.so
/usr/lib/x86_64-linux-gnu/libtinfo.so.6
/usr/lib/x86_64-linux-gnu/libtinfo.so.6.2

as for symlink : 
ln: failed to create symbolic link '/usr/lib/libtinfo.so.5': File exists

What can I do to fix that please ? Thank you very much !

**Comment by jlariviere1** [comment]
after trying these steps, i'm still getting the error

**Comment by Mywifi** [comment]
sudo apt-get install libncurses5
