### ISSUE TITLE
implementing NFS

### ISSUE THREAD

**Issue by karthikeyan1038** [ArweaveTeam/arweave#239]
Hai, I have very many server each have arweave-sync is running, For syncing blocks, txn, wallets, wallets-list, and data. Shall I use NFS server with 3 TB hard disk?. what is the best solution for synchronizing all the data's to all the servers?

**Comment by ldmberman** [comment]
Hi, @karthikeyan1038 

I apologize for the late response.

You may just let each of the servers download the data. Alternatively, if you already have data on one of the nodes, you could use rsync to copy it around.

I recommend joining [our Discord server](https://discord.gg/DjAFMJc) where our miners frequently discuss various setups they experiment with.
