### ISSUE TITLE
Add log rotation to session log

### ISSUE THREAD

**Issue by themue** [ArweaveTeam/arweave#24]
Today new sessions logs get created when starting a node and grow during uptime. During long uptimes this can lead to quite large and unusable logs.

This has to be changed into configurable log rotation intervals. While the active and the first archived log should be uncompressed all other ones have to be compressed.

Configuration arguments:

- Log rotation interval
- Log rotation size (to be discussed: rotate already when size is reached before end of interval)
- Number or archived logs before getting deleted or moved

**Comment by ldmberman** [comment]
Logrotation was introduced [here](https://github.com/ArweaveTeam/arweave/commit/f8f4771b465d09e92a59096344aba31b2ab7cff6).
