### ISSUE TITLE
Minimum number of confirmations available in transaction?

### ISSUE THREAD

**Issue by septs** [ArweaveTeam/arweave#240]
The minimum number of confirmations available (can get data stably) in the transaction?

**Comment by ldmberman** [comment]
Hi @septs,

Sorry for the late reply.

Most of the time it should be settled after one or two confirmations, but if you want more confidence I would recommend to wait for about 15 confirmations.

The data (what you get from `/tx/<id>/data`) is usually distributed separately so a particular node may receive it some time after the tx gets the first confirmation.
