### ISSUE TITLE
Transactions are not include into the block

### ISSUE THREAD

**Issue by zhjjj** [ArweaveTeam/arweave#247]
I have been working on the AR wallet for days with the JS sdk. It was working great but since today some transactions are not include into the blocks.  I submited the transactions and got the response 'OK'
So I try to find why and found something that I need to confirm. 
1、In JS SDK, the transaction body 'last_tx' try to call **getTransactionAnchor** . But I check the SDK in GO and Scala, they call to get the wallet last_tx. And if the wallet has not ever submit a transaction, the return value is empty. The API doc also mentioned that `The last outgoing transaction ID from the sending wallet. If this is the first transaction from the wallet then an empty string should be used.` But when I use the default way that use `getTransactionAnchor` yesterday, the transactions success too. So what should I use for the 'last_tx' params?
2、In every transaction I try to get price from API, then package the transaction then sign then submit it. Is it possible that the reward is not enough? Should I specific more reward to make the transaction accepted by the miner faster?
3、Can I transfer all the balance to another wallet (exclude the reward of course) ?

I tried different params to build the transaction and submit them. All the submission results are 'OK' but none of the really succeeded.

So please help me about this issue. Thanks!

**Comment by zhjjj** [comment]
I found that if I pass some data into the transaction, it will finally succeed.
Is it a bug or something I missed?

**Comment by ldmberman** [comment]
Hi @zhjjj,

1. Using the last outgoing transaction ID for "last_tx" allows for only one TX per wallet per block - if you submit several such TX close in time, they will be accepted, but only one of them will be confirmed. It is an old way of building transactions. Go SDK and Scala SDK still build transactions this way - they haven't been updated for a while, unfortunately. The new approach, which does not have the one tx per wallet per block limitation, is to set last_tx to what's returned by GET /tx_anchor. This is what JS SDK's getTransactionAnchor does. The endpoint returns the hash of the block with 25 confirmations. In case you wonder, the purpose of the "last_tx" field is to prevent transaction replay - nodes only need to have the latest blocks and balances to determine that a transaction is unique, there is no need maintain a complete set of historical transactions to be able to accept new ones.
2. The reward estimate returned by the API (GET /price/{bytes}) is conservative - it accounts for the possible increase of the reward in the short term.
3. You can transfer all your tokens to another wallet off course. However, note that if you make a transfer to a new wallet, there is an extra 0.25 AR fee.

Hope this helps.

**Comment by zhjjj** [comment]
Hi @ldmberman 
  Thanks for your help. 
  But why the transaction without `data` does not succeed? That's the only reason I found to explain why some transactions succeeded and the other transactions failed

**Comment by ldmberman** [comment]
@zhjjj which last_tx did these txs have? Could you share the transaction identifiers?

**Comment by zhjjj** [comment]
@ldmberman this one failed
{"format":2,"id":"HoQoCsq-38dVFB4moC7bYvnA2qDcDCmuwaJr1eEmIU4","last_tx":"2J2AQc6vzBkP5qBaXoU6GbkC13RNeTYPpEoo2zE546zzPauS50yIguBoN1noMewW","owner":"n0XX6XSZ-aHeIytUBfP_Vj7UWJpk9Wfbk87esGBOGUkpuDSyM1T3XlDwyMlW4ggDATqBLceha_qA-2FAHJwRtR1VAsftXrxj7TMmv3iCGnRSXM51gAFRIlkGSR-MMgfBkjYlXtaA5-H2zr4P0gIYBc5EfH15DtG2qZ_CLYdn0CklTGfXVp3ed5sErw7GMfOv4vUT6s0dehllZYLAAPlLj4AwQY9J0YVNOFP5hTkXg2XaUEavdMUO0u4u-qYMt8xs4Ih5q_NTAsx87scRV3Ed9Xg5OlJATZW8olZk4CLnbYZUH08cCwTaqns9pHsWSrZX_HMh7dgiX0DkC4HbjjwR8AkCgMOFuqNtXjCMP7R7V8Nis4oOWefxKaU6OHCJhlZE8yukteFDHcpgn-iOfhVCaNNUD71ItLwQ1ge1WHWJwOQLCA1_37LGzLJwXymHzWXg20RJ1HRAsOqwizO3kQwGW8bvFZMOiPHc-5kuVjtKl0WEPqaK0IYhcM6SFGux5N5Z2I8g2Co_VKdTY2axD0DmiQvZAZLeUe_zRldbnzz6-dyKdeteJjAUxCblzB9vOWuSMvQhrWzhZyTiaYKV1dc2RtNvbTsmTjhDkhi3t0CovcKCifCncM9Ziig_JXu-Cj18v_qN8A_yyA_UBaHg9sp8v3Co1FdOBSPNA8KgeWh4eu8","tags":[],"target":"6RfVWDy8aniWDnrKvxs18QBMnBM8Kw7X28IRmUckRvg","quantity":"20000000000","data":"","data_size":"0","data_root":"x9bUbvLyiRlsOOqClNkKV0LAohFd-PfXfb_XoYosfQI","data_tree":[],"reward":"1251325","signature":"ZlNkAYQexF30ejbd7Capk5hkydJYk-eEzT_Is3U5KSNbYv1eCCpmjUgB99Eg0AKaD2Gspfar4D-8zUwLbukeaxoF4qw0avC6Q2G4mADaoNqBVmRU1JrihmPJhZUBDb8bJD1wkKeaZH_zvzSn2XTsMGtjk2K2k4XRIVH22NLVIqNbSwZkcjN6C1NoWjFEJpFZsI14LCAgH8QC0xZ4kXBeWTLzoTVrmxxzlsYrMaV31n8zJ0Xo2f_aNqBxNc1AqoqXl_9uluD4NgraLM2hGtgbKxvp7eE-clWv1wx1rS3KdGxfDcO-9Bvn82nG1lwiZ0aIJsGFMaD3OG8JAxP8EXmUljq4sPrRnuCTARHCkbM8HGzRrsD5kr5L5DvQVy_pgRrwZR7I2lfCtPr7bium1-Q5IfsUJwqQOs1lyAdp32pNK20ZCP7__HIW_JYQVi2gudZ6d7TeheexW9oaW9yuNsviuKx_XOvGWiYsn5QAXCUsifV8vlCHeXhqrN8CTPr8g7P9LE6lsM1rGVeTRbeFH9eX2p0wgdSob__klkRINQehY0xd7ZuKHMGiIlAv3NjmforVTEva_36ujjlwiv6uWwDqZjIfomkhLwIgWjj45R7L9tC9XCr3M5cW9vSyOwNJTHtzCm9sf7-mo_fVZan-lTMmhd6fV9hEGyatCkS87kl02vY"}

**Comment by ldmberman** [comment]
@zhjjj hm, you should've got a 400 response, it has 0 for data_size but a non-empty data_root. How did you build it?

**Comment by zhjjj** [comment]
No, I got a 200 response with message 'OK'. 
And I build the transaction with the JS SDK. I give the `data` an empty String, and the data is transfer to UInt8Array with length 0 at [here](https://github.com/ArweaveTeam/arweave-js/blob/master/src/common/common.ts#L102). So the `attributes.data` is not null and execute the data_root calculation.
Maybe I should give the `data` null, but I got the `empty string` information from [here](https://docs.arweave.org/developers/server/http-api#submit-a-transaction)

**Comment by ldmberman** [comment]
@zhjjj I see, thank you for the clarification!

We are dealing with two issues in two different places here.

The first one is that our new gateway [accepts invalid transactions](https://github.com/ArweaveTeam/gateway/issues/2). If you want to see error responses until it's fixed, you can post directly to nodes - `http://lon-1.eu-west-1.arweave.net:1984`, `http://lon-2.eu-west-1.arweave.net:1984` are the ones I would recommend.

On the second matter, I've just opened [a JS SDK issue](https://github.com/ArweaveTeam/arweave-js/issues/37). As a workaround, you can send an empty space or any other char, you won't notice the fee difference anyway.

**Comment by zhjjj** [comment]
@ldmberman Thanks for your response. 

The gateway with transaction validation will do much help for us!
Looking forward for the release~

**Comment by ldmberman** [comment]
The issues have been long fixed in the JS SDK and the gateway. Please, reopen if the issue occurs again.

**Comment by crossle** [comment]
```
{"format":2,"id":"c0JBMp4eV6pZtRrEG8YDhPvnWCpYfTgQb7KaxgYRjVI","last_tx":"tKi6-eXSHaX35uDyG7wh5T-RMi6YY80YTOWxwoirozRIrmVvifLpF70k5VEady2V","owner":"sbgpfO5ArcxT9P83PjtxKetixARBvOOJAHAonx_l39RUICQvC4ChYxlHRSrSLwnL6cRiVBRF1SER4xrcSqtaIJBPKAjWNgvBTzSD7bmVCLn_RwTpnSxno_s_XOsS3q_ha7BPgSUNfMFew_tdhI_UKxJ9BXvy1bn0n2dO5n1yAAzbmX5eFHXKW_rCYU9Zx097eLMrD-BypeuATFRRN4fVB5OZ3B_6OsegTdRp3ihvRw6JG6bMYuJyEyz2ruuSvB8Rq6y9N8lUf4Uc-TR_YrlhJeDXw1H2vVxWnen0zzOnjDx_vutopNOOU_RHKTdGtTaQyt509lxP34fauFLm7LKOFL6PEkJlDjwG55GjM979bcqy7mM8OEvHGK0SoWh7OsH1xSfLBI_0GG_C4qkWPDqkNSNXzj81-SueTnh2YrCX8bC0YOno18UFWqbXrs7Ts4Nekgdxc1tIhjUl5RLp7N47Qt3He1spZnbHjgUOqERt2q6lwOr7JeuuFKv2684DPCEGWPWwkj97Lb3jvzOIL227yHv7sJLZ8T0AKFc_5jx2ifkJIVcIcGxGqEPOrORdBzLAUdwipMtavfS8OWtpTALPkHJcsdH53-GSSzWE645nexdehblcVd0fxZYIFP_T-ErGKnwUO4kgFdkk3Ar4Oo-VzLKixhXE9rs3q8rScJ1t_ls","target":"C3uDwZ3uWMHhZPnf6lWTXXJWy_Qy7BPsbBWNWlqZoMY","quantity":"500000000000","data":"","reward":"15000000000","signature":"QEU13FjohRZuwB1ZhWZX7aWTHCtvmjxCRmzItAIJ9OdSVESC_9iN53VzW_OTgqJoA9EajFcAQ5Fv2BgrXgVv5O1eWohzOmKwItxTwEPRf055SPkcHKdmq1ObxP0U9xJwiR3_gdceYWr-bnL7f2QYZjmYJTICA5ho9B2RQc95RF0owyw0mTj91uhG1BBSppaRqFx9Cro86fv_SpW5AE_iKH0v98OdJ8182F6-4aDl1zXJpBjCgsTIvWkfsj7qP4Ly7wzoOAY5t9apdaMVfxhb5-70cXXeUT24BzyvtwteWF0lkM7S-tCQmgW0Z4A0tAPpiUCsjPyUHAznpVzLTlea_q8U9_Qg_EG2NW5LnVtp_JfGmY0bTcykn2Ss_Ff0Lf87iIgwhmzlspL7PmNlUBrPFfISjHhh_qJIWwSNLm7Amv6P4uPcVkKzVaGefYaGDSebAh3lo-ALjVviBlNAaKs2VnvcVZFYr1tuh5u1-0aTJcpbrDBHP0w2rvBZViSvdqMUiXjeAN4tDQAxDtTbNGZMiMa0iZGdYTi7JanyeJxrkL67sEjBcfe_BSxij6sxBbiBUcpSBZu-QHpDseP1h71GQBAxHG53KRhKaQ_MwFe-wTPLl-0G_3uFM2jSk6RGvm3ELxG0_kzrTbAaLGkhGbA3ctX4tQm58hlh6_D2jNVtFgQ","tags":[],"data_size":"0","data_root":"","data_tree":[]}
```
I broadcast the tx no success, any sugguest?
