### ISSUE TITLE
413 Payload Too Large Error for Submitting V2 Transaction

### ISSUE THREAD

**Issue by touhonoob** [ArweaveTeam/arweave#251]
Arweave gateway doesn't support submitting big files even with v2 transactions since the max payload size is limited to 15MB.

https://github.com/ArweaveTeam/arweave/blob/e9aa880138e955cbdddcff4ecd3538c2d70a985e/apps/arweave/src/ar.hrl#L108

**Comment by ldmberman** [comment]
@touhonoob hi, this limit only applies to data sent along with the transaction header. It's a convenient but expensive way to submit data. Large files have to be submitted chunk by chunk via the new POST /chunk endpoint.

**Comment by touhonoob** [comment]
@ldmberman thanks

**Comment by touhonoob** [comment]
@ldmberman I can't find any doc on how to use the POST /chunk endpoint. Could you point me to that please?

**Comment by ldmberman** [comment]
@touhonoob hey, unfortunately, there is none yet. However, @aidanok and @arweave-kyle are working on the new version of arweave-js and gateway, which will support chunk uploading.

**Comment by aidanok** [comment]
hey @touhonoob, you can view the current work on the client-side of uploading chunks here: [https://github.com/ArweaveTeam/arweave-js/tree/feature/2.1-chunk-uploading](https://github.com/ArweaveTeam/arweave-js/tree/feature/2.1-chunk-uploading)

**Comment by touhonoob** [comment]
@aidanok That helps a lot. Thanks

**Comment by aidanok** [comment]
@touhonoob No probs, you can drop into developer discord https://discord.gg/BXk8tq7 too if you want to discuss or have any quick questions.
