### ISSUE TITLE
Unable to login through Google

### ISSUE THREAD

**Issue by raghavnarang** [ArweaveTeam/arweave#252]
While trying to claim the token, I tried to login through Google. After logged in from google side, nothing shown on arweave. But I got this access_denied error in the console.

![N3s7V8A](https://user-images.githubusercontent.com/35099883/87257531-53137780-c4b9-11ea-97c1-533fadffb80a.png)

**Comment by vkatsuba** [comment]
Hi @arweave-kyle could you take a look to this issue? Looks like this issue need to move to https://github.com/ArweaveTeam/website repository or maybe into another repository. Thanks.

Regards,
--V

**Comment by vkatsuba** [comment]
Hi @raghavnarang,

Thanks for bug reporting. If you can, please, provide more detail about this issue:
- What OS type and version you use?
- What browser you use?
- What version of browser you use?

Thanks.

Regards,
--V

**Comment by arweave-kyle** [comment]
Hey @raghavnarang, for support issues with the website it’s best to just drop us an email, but no worries.

If you download the web extension, generate a new wallet, and send us your address we can send you 1 AR to get started that way :)

You can email us at team@arweave.org, or drop by our community discord server and DM me the address.

You can find our discord community here: https://discord.gg/BXk8tq7

The wallet for chrome/brave: https://chrome.google.com/webstore/detail/arweave/iplppiggblloelhoglpmkmbinggcaaoc?hl=en-GB

Or for Firefox here: https://addons.mozilla.org/en-GB/firefox/addon/arweave

**Comment by vkatsuba** [comment]
Hi @raghavnarang,

Looks like this issue can be close. If your issue still relevant, please follow by steps what was described by @arweave-kyle.

Regards,
--V
