### ISSUE TITLE
Compile error on macOS

### ISSUE THREAD

**Issue by goomario** [ArweaveTeam/arweave#253]
I used the "./rebar3 compile" command to compile an error. as follows:
```
Undefined symbols for architecture x86_64:
   "_enif_alloc", referenced from:
       _init in ar_mine_randomx.o
   "_enif_alloc_resource", referenced from:
       _init in ar_mine_randomx.o
   "_enif_free", referenced from:
       _init in ar_mine_randomx.o
```

Use the solution given in http://erlang.org/pipermail/erlang-questions/2011-June/059679.html to modify the `apps/arweave/c_src/Makefile` and compile it.

Erlang: version 22
Clang: Apple clang version 11.0.0 (clang-1100.0.33.17)

**Comment by ldmberman** [comment]
Hey @goomario, which compiler do you have registered under the gcc alias on your system, I mean, what's in `gcc -v`?

**Comment by goomario** [comment]
% gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin19.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by goomario** [comment]
> Hey @goomario, which compiler do you have registered under the gcc alias on your system, I mean, what's in `gcc -v`?

% gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin19.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by goomario** [comment]
I submit a pull request #254 , it's compile pass for me.

**Comment by ldmberman** [comment]
@goomario I see, thank you. Hm, it does work on my Macs. Which OS version do you use?

**Comment by goomario** [comment]
> @goomario I see, thank you. Hm, it does work on my Macs. Which OS version do you use?

OS Version: 10.15.5

I compiled it with OS default gcc, and did not set the alias to gcc-9. Could it be caused by this problem?

**Comment by ldmberman** [comment]
Interesting, I am on 10.15.5 too, also running the default clang. However, I have version 11.0.3 (vs your 11.0.0, but judging by the version format it should not make such a difference), and the prefix it was compiled with is in my case `/Library/Developer/CommandLineTools/usr`, on two machines. Do you have the command line tools installed?

**Comment by goomario** [comment]
> Interesting, I am on 10.15.5 too, also running the default clang. However, I have version 11.0.3 (vs your 11.0.0, but judging by the version format it should not make such a difference), and the prefix it was compiled with is in my case `/Library/Developer/CommandLineTools/usr`, on two machines. Do you have the command line tools installed?

I'm installed xcode command line, but not upgrade to newest.

**Comment by goomario** [comment]
I test pass by `LDFLAGS = -arch x86_64 -flat_namespace -undefined suppress`, look like LDFLAGS has set.Should you consider always setting "-flat_namespace -undefined suppress" in the Makefile configuration?

**Comment by goomario** [comment]
Maybe my dev env problems. 

My Makefile:
```
ifeq ($(UNAME_SYS), Darwin)
	CC ?= cc
	CFLAGS ?= -O3 -std=c99 -arch x86_64 -finline-functions -Wall -Wmissing-prototypes
	CXXFLAGS ?= -O3 -arch x86_64 -finline-functions -Wall
	LDFLAGS ?= -arch x86_64
	LDFLAGS += -flat_namespace -undefined suppress
else ...
```

thank you very much.

**Comment by liuchengxu** [comment]
#254 also fixes the compilation for me. I'm using 10.15.7,

```bash
~/.../ArweaveTeam/arweave ❯❯❯ gcc --version                                                                                            (master) (03/02 12:36:38)
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by ldmberman** [comment]
@goomario thank you for the patch!
