### ISSUE TITLE
A Lot of "Unhandled message" Logs in Log File

### ISSUE THREAD

**Issue by jq8778** [ArweaveTeam/arweave#258]
Got a lot of msgs in log file.
The Msg is like this:
** Undefined handle_info in ar_downloader
** Unhandled message: {gun_data,<0.32483.1615>,
                                #Ref<0.3188984720.2183659521.233483>,nofin,
                                <<"_H6iTbiOkVDSpsYjVgR3z1fs_fU3Hb3uXbxziR4e5YeKWltXOqQ8P5L7mtHmzZxj0SA5OWkeBoHbpui-Tdw4-aCeAkJgBhlQBNoLxtqhwa-yJx0RL7EBIkyohZ4GYo2t6h5itRbScKEhKSOcPDGgV4bay4J9y0LZVOkhyYM1iSnKIpnY-DqVWlpCN7lUiG4iJ5iKh6WxrQSGPFUV0yyPY4_pbsy9WKtzbcouu-6Ey5qQcJIwJiqGB8WMGVLQZzpl1NQr0jOVrU3HU272VtogAtOGKY6bGlZsgemZjcZoIZpV7HNi-braRwAbGaEAYlHgELBj0OGRjeISaBhwYNIZg4iEotCDEYZFpgEDHvRzmleARiIgc4BQMzx4q3UySUJvGW5doO4VAtqKFV-8CTIKHDb1wc09XLKke5YuMszLWRqXFsE2ngUwDgKLOwZkO0hKQ9bdPks0PDLyJgryvs1LqBQKK6d4WAdAvOzNxZE6TadcG9KX4dyVcHu6Q9lFclLkX8UlTiDrsQEe5llIW1PQCBn0pdQCTo5DkWRkcJYDBZhrJJWKMy0a5F5Q5aURYjLEbCoIAX5dF3OM7CWpJDDT6VJ_DBqmsPWa0EfT86i7qdhNMRcegeBYBkBJzkQc5LzMMgfr49g4ozQTYYSBMYQskBeF8fKZIQICZZbhDlcHeehc4NHjuNRza6xsWeupmLLA1Q4bqA5OUKHlx1a1_nO4WKXjQd942D0ABvMKjGkRQcrXyyNP_64GyzDLUACu9_0OuYfHKuyiqPaemKJyHXSa3h8cohHGv9liZV96bYktCroNmnPQGPSGwCmDFFrQAReCJtZW6W5TWHTKsaWJRGgCzsqFGggSBJwhQ_VydhSK6GimRTvUvAjVnW25qU73ulWq2NRN75GznGnEL6HU-oCguZVXVFSJQBQLOeVoSA4X6J8rQ9qJAbM0QqI0aE3DFLYWyKMFip9AmFicuQEqTd0qjTbTQSi0vNKcoSjtQV_-T1sWHBpQgbKDTMn4rrQJZa1Imig43AEGHZgZtrwdYRGJohwi6aqwGYGhCsGgixxJ2aMhBgIFT5QOVBcBAg2YIDlYaXmBAcERQuLYpG5wAoAqVWUIUhoYxMgEgoImbtCY6jehpF6rBHIfZM6owdn8oYHLHHjcgA****">>}
For security Reason we hide part of send data, it seems like a tx.
This type of msgs happen randomly and while it comes up, it will give thounds of lines in log files, which means we actually got thounds of warning.
Seems the gunserver meet some errors and result this.

**Comment by ldmberman** [comment]
Fixed in the new release, please, reopen if the issue persists.
