### ISSUE TITLE
The last_tx of the two transactions is the same

### ISSUE THREAD

**Issue by xuyulinnn** [ArweaveTeam/arweave#263]
SR24xtQxvSMfH64FYsgVdl5WTPWB9i3a7AGMdTSQFRQ
Uy2XPqR1pDn-9aSg1e0JFh_Vqo_bAArQs8hgLHFSacg

![image](https://user-images.githubusercontent.com/24400773/92564625-0b884c80-f2ac-11ea-9a42-50c0f142b03d.png)

![image](https://user-images.githubusercontent.com/24400773/92564658-19d66880-f2ac-11ea-8133-f6c461d3bd03.png)

The last_tx of the two transactions is the same
is this normal？

**Comment by ldmberman** [comment]
@xuyulinnn hi, yes, `last_tx` is either a TXID or a hash of one of the last 50 blocks. The name is misleading.
