### ISSUE TITLE
Hope to be able to query by block height

### ISSUE THREAD

**Issue by 90hacker** [ArweaveTeam/arweave#288]
The current interface can only be queried based on `block_hash`。
```
https://arweave.net/block/hash/{block_hash}
```
Hope to add block height number to query block details。

**Comment by mcmonkeys1** [comment]
You can in fact already query by height:
`https://arweave.net/block/height/510000`

**Comment by 90hacker** [comment]
> You can in fact already query by height:
> `https://arweave.net/block/height/510000`

I did not find it in the development documentation.
Thought there was no interface.
Thank you.

Also ask, will you plan a Java-Sdk package in the future?

**Comment by ldmberman** [comment]
Hey @90hacker, the Arweave team only maintains the [Typescript SDK](https://github.com/ArweaveTeam/arweave-js). Other SDKs are created by the community, I haven't heard about the Java one though.
