### ISSUE TITLE
is there any plan to provide data downloading service for faster sync data for miners

### ISSUE THREAD

**Issue by AndyChenW** [ArweaveTeam/arweave#292]

**Comment by ldmberman** [comment]
Hi @AndyChenW , what is the biggest value you tried for the `sync_jobs` parameter? You can increase it further, and if your Internet speed allows that, you can definitely reach tens of megabytes/s and download several terabytes a day.

**Comment by BertBats** [comment]
сб, 20 февр. 2021 г. в 17:24, Lev Berman <notifications@github.com>:

**Comment by AndyChenW** [comment]
thx @ldmberman

**Comment by maxbelz** [comment]
the question is still actual. i want to sync data at another internet connection ( just download files to hdd and than copy it to ssd on farmer machine) i dont have really fast internet in the place where mining-machine located.
