### ISSUE TITLE
Error in Erlang

### ISSUE THREAD

**Issue by homepagecn** [ArweaveTeam/arweave#300]
**After running ./bin/start , prompt :**

Launching Erlang Virtual Machine...
Exec: /usr/lib/erlang/erts-10.6.4/bin/erlexec -noshell -noinput +Bd -boot /home/ar1/arweave/_build/debug/rel/arweave/releases/2.4.1.0/arweave -mode embedded -boot_var ERTS_LIB_DIR /usr/lib/erlang/lib -config /home/ar1/arweave/_build/debug/rel/arweave/releases/2.4.1.0/sys.config -args_file /home/ar1/arweave/_build/debug/rel/arweave/releases/2.4.1.0/vm.args -- foreground +Ktrue +A20 +SDio20 +sbwtvery_long +sbwtdcpuvery_long +sbwtdiovery_long +swtvery_low +swtdcpuvery_low +swtdiovery_low +Bi -run ar main polling sync_jobs 320 data_dir /mnt/arweave enable search_in_rocksdb_when_mining enable randomx_large_pages mining_addr oxMOu7aIsgrzZhYcQ0TDIbrOxjvXozvWVFJCPqkWscQ peer 218.65.176.237 peer 117.34.91.203 peer 183.213.28.159 peer 45.119.4.42 peer 222.99.128.47 peer 18.183.117.97 peer 3.112.172.194 peer 35.201.179.47 peer 45.77.182.243 peer 139.162.111.32
Root: /home/ar1/arweave/_build/debug/rel/arweave
/home/ar1/arweave/_build/debug/rel/arweave
{"init terminating in do_boot",{badarg,[{erlang,list_to_integer,["sync_jobs"],[]},{ar,parse_cli_args,2,[{file,"/home/ar1/arweave/apps/arweave/src/ar.erl"},{line,274}]},{ar,main,1,[{file,"/home/ar1/arweave/apps/arweave/src/ar.erl"},{line,91}]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ({badarg,[{erlang,list_to_integer,sync_jobs,[]},{ar,parse_cli_args,2,[{_},{_}]},{ar,main,1,[{_},{_}]},{init,start_em,1,[]},{init,do_boot,3,[]}]})

Crash dump is being written to: erl_crash.dump...done
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
[os_mon] memory supervisor port (memsup): Erlang has closed

How to solve it?

**Comment by homepagecn** [comment]
I found out that Ubuntu has two versions of Erlang, which may be the problem

**Comment by ldmberman** [comment]
Hi, `polling` accepts a number (of seconds), e.g., `polling 30`. However, the default usually works well so you probably do not have to specify this parameter at all.

**Comment by homepagecn** [comment]
It should work with the latest Erlang
