### ISSUE TITLE
For 2.4.2 miner spora display line always shows MiB/s read: 0 instead of the actual value

### ISSUE THREAD

**Issue by edstewbob** [ArweaveTeam/arweave#304]
On prior versions MiB/s read showed a valid value which could be used to help determine read I/O performance.
<img width="828" alt="Screen Shot 2021-06-09 at 2 01 00 PM" src="https://user-images.githubusercontent.com/14189782/121405580-354dcd00-c92b-11eb-9608-5b6c1341d09d.png">

**Comment by ldmberman** [comment]
Was fixed in 2.4.4.0.
