### ISSUE TITLE
Ubuntu 20.04 installation.

### ISSUE THREAD

**Issue by nicezic0** [ArweaveTeam/arweave#310]
Ubuntu 20.04 installation.

Can you update the info about installing Ubuntu 20.04?
At least, dependency scripts, or Binary files?

Anyway, I got an error installing on Ubuntu 20.04.
``
git checkout stable
HEAD is now at c5fc2f1 Bump release number 47, 2.4.2.0

./rebar3 as prod tar
===> Analyzing applications...
===> Compiling ar_sqlite3
===> Compiling arweave
===> Compiling apps/arweave/src/ar_config.erl failed
apps/arweave/src/ar_config.erl:395: function binary_to_existing_atom/1 undefined
``

**Comment by ldmberman** [comment]
Hey @nicezic0, you need to install Erlang 23+. You can grab the sources [here](https://erlang.org/download/otp_src_23.3.tar.gz).

**Comment by nicezic0** [comment]
I remove erlang from ubuntu 20.04's by apt.

and installed the link, Erlang 23+ properly.

However, it still doesn't work.

```
$ ./rebar3 as prod tar
===> Rebar dependency crypto could not be loaded for reason {"no such file or directory",
                                                                    "crypto.app"}
```

Any plan Ubuntu 20.04 Binary version? or proper install documentation?

**Comment by ldmberman** [comment]
@nicezic0 yep, we have a binary that works on Ubuntu 20 - [link](https://github.com/ArweaveTeam/arweave/releases/download/N.2.4.2.0/arweave-2.4.2.0.linux-x86_64.tar.gz). If you want to build from the sources anyway, you need to install openssl before configuring and compiling Erlang.

**Comment by nicezic0** [comment]
thanks
