### ISSUE TITLE
what can i do when Fatal error in erl_drv_rwlock_destroy()

### ISSUE THREAD

**Issue by hxuchen** [ArweaveTeam/arweave#316]
![image](https://user-images.githubusercontent.com/63218494/129690586-6382bce5-1729-47b8-993b-53b8ffa46054.png)

**Comment by ldmberman** [comment]
Did you configure HugePages? You may need to reboot the system.

**Comment by hxuchen** [comment]
> Did you configure HugePages? You may need to reboot the system.

yes!Thanks for your reply.
