### ISSUE TITLE
Mac M1

### ISSUE THREAD

**Issue by rovo79** [ArweaveTeam/arweave#319]
Hello,

If I compile this on my Mac, is it possible to run and mine blockweave?

**Comment by mcmonkeys1** [comment]
Due to the M1 hardware, you would need to disable AES hardware acceleration in the miner. AES computation would then need to be done in software emulation. This is going to be a big performance hit on your hashrate.

**Comment by fabiobi82** [comment]
> Hello,
> 
> If I compile this on my Mac, is it possible to run and mine blockweave?

Hi,
how to compile on Mac M1 from source?
