### ISSUE TITLE
Looback addresses should not appear in the HTTP API peers list.

### ISSUE THREAD

**Issue by codybartfast** [ArweaveTeam/arweave#32]
When accessing "/peers"  through the HTTP API the returned list of peer addresses sometimes includes loopback addresses such as 127.0.0.9 and 127.0.0.1.

Loopback, Private, Link-Local and other reserved address should probably not be returned through the public HTTP API. (RFC 5735 has a succinct table of IPv4 special use addresses).  Perhaps the server should filter out these addresses even if they are configured?

Perhaps there needs to be a distinction between "public" and "private" peers (assuming folk want their own servers talking directly to each other)?

**Comment by themue** [comment]
Thanks for the good feedback.

**Comment by samcamwilliams** [comment]
Thanks @codybartfast -- fixed in b031d4dc21600cc3a2443ff35098a8b1a7af2a52.

Best,
Sam
