### ISSUE TITLE
Running node problem

### ISSUE THREAD

**Issue by jackiesunhoo** [ArweaveTeam/arweave#327]
Launching Erlang Virtual Machine...
Exec: /opt/ar_online/erts-11.1.4/bin/erlexec -noinput +Bd -boot /opt/ar_online/releases/2.4.4.0/start -mode embedded -boot_var SYSTEM_LIB_DIR /opt/ar_online/lib -config /opt/ar_online/releases/2.4.4.0/sys.config -args_file /opt/ar_online/releases/2.4.4.0/vm.args -- foreground +Ktrue +A20 +SDio20 +sbwtvery_long +sbwtdcpuvery_long +sbwtdiovery_long +swtvery_low +swtdcpuvery_low +swtdiovery_low +Bi -run ar main
Root: /opt/ar_online
/opt/ar_online
Usage: arweave-server [options]
Compatible with network: arweave.N.1
Options:
{"init terminating in do_boot",{badarg,[{io_lib,format,["max_propagation_peers (num)","The maximum number of best peers to propagate transactions to. Default is ~B."],[{file,"io_lib.erl"},{line,202}]},{ar,show_help,0,[{file,"/root/arweave/apps/arweave/src/ar.erl"},{line,155}]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ({badarg,[{io_lib,format,max_propagation_peers (num)The maximum number of best peers to propagate transactions to. Default is ~B.,[{_},{_}]},{ar,show_help,0,[{_},{_}]},{ini

Crash dump is being written to: erl_crash.dump...done
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
[os_mon] memory supervisor port (memsup): Erlang has closed
Arweave Heartbeat: The Arweave server has terminated. It will restart in 15 seconds.
Arweave Heartbeat: If you would like to avoid this, press control+c to kill the server.

**Comment by ldmberman** [comment]
Was a bug of starting without arguments, fixed in [the latest release](https://github.com/ArweaveTeam/arweave/releases/tag/N.2.5.0.0).
