### ISSUE TITLE
Timestamp of a transaction creation

### ISSUE THREAD

**Issue by nicolasverlhiac** [ArweaveTeam/arweave#342]
Hello,

Would it be possible to know the timestamp of a transaction creation?

Currently, when we get a transaction with `arweave.net/graphql`, we only receive the block timestamp, not the timestamp of transaction's creation.

The idea behind this question is to be able to know the "age" of a transaction during its pending phase.

What do you think? 

Thank you !

**Comment by ldmberman** [comment]
Hi @nicolasverlhiac, transactions themselves do not have timestamps. Could you, please, expand your motivation a bit - why do you want to know the age of pending transactions?

**Comment by nicolasverlhiac** [comment]
Hi @ldmberman, 
Thank you for your answer :) 

I develop a small tool to follow a transaction during its pending stage. (https://arpending.ownbase.org/)
And I was looking to display the time during which a transaction is waiting to be integrated into a block.
(With a 60 minutes countdown before the transaction wil be rejected)

**Comment by ldmberman** [comment]
I see, thank you for clarifying, nice tool! I would simply record "first seen" - the time when you first find this transaction somewhere.

**Comment by nicolasverlhiac** [comment]
Thanks you, I will use your "first seen" approach. :)
