### ISSUE TITLE
Compile failed

### ISSUE THREAD

**Issue by garysdevil** [ArweaveTeam/arweave#348]
My System Information: "Linux version 3.10.0-1160.42.2.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Tue Sep 7 14:49:57 UTC 2021"

My erl Information: "Erlang/OTP 24 [erts-12.2] [source] [64-bit] [smp:3:3] [ds:3:3:10] [async-threads:1]
Eshell V12.2  (abort with ^G)"

I run the command below:
```bash
git clone --recursive https://github.com/ArweaveTeam/arweave
cd arweave
DIAGNOSTIC=1 ./rebar3 as prod tar > log.txt
```

But compile failed
![image](https://user-images.githubusercontent.com/41293784/152679989-c2816a0e-aa1d-4f8b-afcc-bda8e1400a92.png)
![image](https://user-images.githubusercontent.com/41293784/152680001-822e29cd-4f0a-4737-b158-edca498bcb88.png)

[log.txt](https://github.com/ArweaveTeam/arweave/files/8010123/log.txt)

**Comment by ldmberman** [comment]
Hi, gcc 4.8.5 is too old, try 8+.

**Comment by garysdevil** [comment]
Thank you very much.
Maybe we should update the README.md to avoid this error. GCC 8+ ?
![image](https://user-images.githubusercontent.com/41293784/153457410-215fcaaa-ce89-4b50-a200-3dce030c810f.png)
