### ISSUE TITLE
Enable CORS preflight responses and headers

### ISSUE THREAD

**Issue by arweave-kyle** [ArweaveTeam/arweave#35]
Currently no CORS headers are enabled which limits dynamic embedding of Arweave hosted content.

For example, if I wanted to make an AJAX call to an Arweave node from a browser to fetch the current block height, or get some transaction data, this would fail as nodes don't currently don't respond to preflight requests at all so would be blocked by browsers.

If a webpage with AJAX content is served from the same node the AJAX request is going back to, then this should be allowed under the same origin policy, so I guess this is only really an issue if the webpage is hosted outside of the Arweave network.

I think nodes should respond to preflight `OPTIONS` requests with `Access-Control-Allow-Origin: *` and `Access-Control-Allow-Methods: GET` across all `GET` endpoints at a minimum, although maybe it makes sense to enable it across all endpoints as there are scenarios where will might be useful to be able to post transactions from a browser which is currently only possible using forms.

**Comment by samcamwilliams** [comment]
Fixed in 4aa306f66a4bfe4b59a4330ac34bf68f7a3a4f85.

S

**Comment by arweave-kyle** [comment]
Think we might also need add`Access-Control-Allow-Headers: Content-Type`to allow for clients sending `Content-Type: application/json`on tx post.

**Comment by martin-torhage** [comment]
@arweave-kyle Is the content-type important for that endpoint? Make sense to me to assume it's JSON because that's the only thing we support.

**Comment by arweave-kyle** [comment]
Yeah some http libraries/clients will add it by default, so I think it's better if we support it as some people would need to spend time removing it. Axios JS for example adds a content type by default.

**Comment by mautematico** [comment]
This is not working as expected.

When you OPTIONS/preflight a file, the answer in fact includes CORS headers, however it also includes a redirect to a different host (an arweave subdomain). #271 

```
curl 'https://arweave.net/DBjlUhi51nY85FKPJDim6LtUrg_ttik8oMjz3gBF33A' -X OPTIONS -H 'Access-Control-Request-Method: GET' -H 'Referer: https://permanet.cincel.digital/files/DBjlUhi51nY85FKPJDim6LtUrg_ttik8oMjz3gBF33A'
```
(OPTIONS answer from above curl snippet do have CORS headers, but it is not CORS compliant as it responds with a redirect to a different host)

This gets blocked on every browser other than crhome, thus making impractical to use permaweb resources on, let's say, Firefox or an iPad

If by some magic you happen to know which the subdomain is and try to directly GET said file, the preflight request will answer 404 as OPTIONS it is nonexistent

```
curl 'https://bqmokuqyxhlhmphekkhsiofg5c5vjlqp5w3cspfazdz54acf35ya.arweave.net/DBjlUhi51nY85FKPJDim6LtUrg_ttik8oMjz3gBF33A' -X OPTIONS -H 'Access-Control-Request-Method: GET'
```

```
{"status":404,"error":"Not Found"}
```

this won't work even on chrome.


Any suggestions?
