### ISSUE TITLE
Data deduplication

### ISSUE THREAD

**Issue by nicolasverlhiac** [ArweaveTeam/arweave#351]
Hi,

I may be wrong but I understand that there is no data deduplication in the storage on arweave.
**No data deduplication** : as each new data item is added to the chain.

Is such a mechanism planned? 
Or is this not a constraint on the scalability of the network?

Thank you for your answer :-)

**Comment by ldmberman** [comment]
Hi,

There is no deduplication indeed. There are two upsides to it - the design is much simpler, and it allows people to pay for higher redundancy compared to what they get by default (although the defaults are estimated to be safe). We do not see it as a scalability constraint - duplicates do not receive a better price, and they are not expected to occupy a large proportion of the uploaded volumes.

**Comment by nicolasverlhiac** [comment]
Thank you @ldmberman for your answer.
Upsides makes sense indeed, what I thought would be a constraint is actually a good thing for the network.
