### ISSUE TITLE
Not enough disk space reported on startup

### ISSUE THREAD

**Issue by arweave-kyle** [ArweaveTeam/arweave#36]
The following error intermittently gets reported on startup which stops the node loading any further.

```
=ERROR REPORT==== 15-Aug-2018::21:25:25 ===
Error in process <0.884.0> with exit value:
{badarith,[{ar_storage,enough_space,1,
                       [{file,"src/ar_storage.erl"},{line,391}]}
```

Nodes in question have plenty of space available so this is not accurate,  restarting them again works fine, sometime it may take 1 or 2 restarts before it continues.

Debugged by @themue, issue seems to be async calls to `ar_node_db:*(used_space)` on startup. Occasionally we seem to get a race condition where the value hasn't been set, while elsewhere in the application we're trying to read that value which returns `not_found` as it hasn't been set yet, this seems to trigger the error above.

Making sure this value is set before any process accesses this should resolve the issue.

**Comment by themue** [comment]
As an additional info: We have already an initialised `UsedSpace` when the node starts. It's just not set in `ar_meta_db`. So fix is a simple one liner. Adding `ar_node_db:put(used_space, UsedSpace)` in `ar.erl` line 191.

**Comment by themue** [comment]
Done.
