### ISSUE TITLE
/src/ar_join.erl:28 event: not_joining, reason: no_peers

### ISSUE THREAD

**Issue by StayingAlive1998** [ArweaveTeam/arweave#363]
I feel like a bum, be easy on me im new to this whole thing.

Launching Erlang Virtual Machine...
Exec: /home/eric/Documents/Arweave/erts-12.1/bin/erlexec -noinput +Bd -boot /home/eric/Documents/Arweave/releases/2.5.1.0/start -mode embedded -boot_var SYSTEM_LIB_DIR /home/eric/Documents/Arweave/lib -config /home/eric/Documents/Arweave/releases/2.5.1.0/sys.config -args_file /home/eric/Documents/Arweave/releases/2.5.1.0/vm.args -- foreground +Ktrue +A20 +SDio20 +sbwtvery_long +sbwtdcpuvery_long +sbwtdiovery_long +swtvery_low +swtdcpuvery_low +swtdiovery_low +Bi -run ar main mine mining_addr Ucj9jYUwxwDKqF5n2b80Iy2Hd9vou16YEVghcYuz2A0
Root: /home/eric/Documents/Arweave
/home/eric/Documents/Arweave
=ERROR REPORT==== 24-Apr-2022::11:06:54.914773 ===
Error in process <0.688.0> on node 'arweave@127.0.0.1' with exit value:
{{badmatch,{error,{load_failed,"Failed to load NIF library /home/eric/Documents/Arweave/lib/arweave-2.5.1.0/priv/arweave: 'libssl.so.1.1: cannot open shared object file: No such file or directory'"}}},
 [{ar_mine_randomx,init_nif,0,
                   [{file,"/root/arweave/apps/arweave/src/ar_mine_randomx.erl"},
                    {line,297}]},
  {init,'-run_on_load_handlers/2-fun-0-',1,[]}]}

=SUPERVISOR REPORT==== 24-Apr-2022::11:06:54.915472 ===
    supervisor: {local,kernel_sup}
    errorContext: start_error
    reason: {on_load_function_failed,ar_mine_randomx}
    offender: [{pid,undefined},
               {id,kernel_safe_sup},
               {mfargs,{supervisor,start_link,
                                   [{local,kernel_safe_sup},kernel,safe]}},
               {restart_type,permanent},
               {significant,false},
               {shutdown,infinity},
               {child_type,supervisor}]

=CRASH REPORT==== 24-Apr-2022::11:06:54.917666 ===
  crasher:
    initial call: supervisor:kernel/1
    pid: <0.684.0>
    registered_name: []
    exception exit: {on_load_function_failed,ar_mine_randomx}
      in function  init:run_on_load_handlers/0 
      in call from kernel:init/1 (kernel.erl, line 189)
      in call from supervisor:init/1 (supervisor.erl, line 330)
      in call from gen_server:init_it/2 (gen_server.erl, line 423)
      in call from gen_server:init_it/6 (gen_server.erl, line 390)
    ancestors: [kernel_sup,<0.658.0>]
    message_queue_len: 0
    messages: []
    links: [<0.660.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 29
    reductions: 227
  neighbours:

=CRASH REPORT==== 24-Apr-2022::11:06:55.917324 ===
  crasher:
    initial call: application_master:init/4
    pid: <0.657.0>
    registered_name: []
    exception exit: {{shutdown,
                         {failed_to_start_child,kernel_safe_sup,
                             {on_load_function_failed,ar_mine_randomx}}},
                     {kernel,start,[normal,[]]}}
      in function  application_master:init/4 (application_master.erl, line 142)
    ancestors: [<0.656.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.658.0>,normal}]
    links: [<0.656.0>,<0.655.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 29
    reductions: 165
  neighbours:

=INFO REPORT==== 24-Apr-2022::11:06:55.920275 ===
    application: kernel
    exited: {{shutdown,
                 {failed_to_start_child,kernel_safe_sup,
                     {on_load_function_failed,ar_mine_randomx}}},
             {kernel,start,[normal,[]]}}
    type: permanent

{"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,ar_mine_randomx}}},{kernel,start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,ar_mine_randomx}}},{kernel,start,[normal,[]

Crash dump is being written to: erl_crash.dump...done
Arweave Heartbeat: The Arweave server has terminated. It will restart in 15 seconds.
Arweave Heartbeat: If you would like to avoid this, press control+c to kill the server.
^C
Command 'peer' not found, did you mean:
  command 'peet' from deb pipexec (2.5.5-2)
  command 'pee' from deb moreutils (0.66-1)
  command 'peek' from deb peek (1.5.1+git20211214-1)
  command 'pear' from deb php-pear (1:1.10.12+submodules+notgz+20210212-1ubuntu3)
  command 'beer' from deb gerstensaft (0.3-4.2)
  command 'seer' from deb seer (1.1.4-6)
Try: sudo apt install <deb name>

**Comment by StayingAlive1998** [comment]
TCP connection timeout?

**Comment by StayingAlive1998** [comment]
I installed libssl1.1.1 with this https://linuxpip.org/install-openssl-linux/ . Im here now. 
2022-04-24T13:38:20.211601-04:00 [info] /root/arweave/apps/arweave/src/ar_meta_db.erl:97 event: ar_meta_db_start
2022-04-24T13:38:20.211843-04:00 [info] /root/arweave/apps/arweave/src/ar_arql_db.erl:165 ar_arql_db: init, data_dir: .
2022-04-24T13:38:21.237233-04:00 [info] /root/arweave/apps/arweave/src/ar_arql_db.erl:375 ar_arql_db: creating_meta_table
2022-04-24T13:38:21.310095-04:00 [info] /root/arweave/apps/arweave/src/ar_arql_db.erl:389 ar_arql_db: creating_schema
2022-04-24T13:38:26.815225-04:00 [info] /root/arweave/apps/arweave/src/ar_header_sync.erl:47 event: ar_header_sync_start
2022-04-24T13:38:26.877500-04:00 [info] /root/arweave/apps/arweave/src/ar_data_sync.erl:208 event: ar_data_sync_start
2022-04-24T13:38:27.107214-04:00 [warning] /root/arweave/apps/arweave/src/ar_join.erl:28 event: not_joining, reason: no_peers
2022-04-24T13:38:28.216425-04:00 [info] /root/arweave/apps/arweave/src/ar_blacklist_middleware.erl:29 event: ar_blacklist_middleware_start
2022-04-24T13:38:28.217399-04:00 [info] /root/arweave/apps/arweave/src/ar_poller.erl:34 event: ar_poller_start

Launching Erlang Virtual Machine...
Exec: /home/eric/Documents/Arweave/erts-12.1/bin/erlexec -noinput +Bd -boot /home/eric/Documents/Arweave/releases/2.5.1.0/start -mode embedded -boot_var SYSTEM_LIB_DIR /home/eric/Documents/Arweave/lib -config /home/eric/Documents/Arweave/releases/2.5.1.0/sys.config -args_file /home/eric/Documents/Arweave/releases/2.5.1.0/vm.args -- foreground +Ktrue +A20 +SDio20 +sbwtvery_long +sbwtdcpuvery_long +sbwtdiovery_long +swtvery_low +swtdcpuvery_low +swtdiovery_low +Bi -run ar main mine mining_addr Ucj9jYUwxwDKqF5n2b80Iy2Hd9vou16YEVghcYuz2A0
Root: /home/eric/Documents/Arweave
/home/eric/Documents/Arweave
=INFO REPORT==== 24-Apr-2022::13:38:20.196762 ===
    alarm_handler: {set,{system_memory_high_watermark,[]}}
Initialising RandomX dataset for fast packing. Key: <<"ZGVmYXVsdCBhcndlYXZlIDIuNSBwYWNrIGtleQ">>. The process may take several minutes.
RandomX dataset initialisation complete.

Did i do it right?

**Comment by rosmcmahon** [comment]
please join [Arweave Miner's server](https://discord.gg/yPKVgjUw). that is the correct place to find answers to all these getting-started & FAQ questions.

**Comment by StayingAlive1998** [comment]
Sure thing.
