### ISSUE TITLE
Unable to sign transaction

### ISSUE THREAD

**Issue by AlexReed19** [ArweaveTeam/arweave#373]
Followed [this](https://edgeandnode.com/blog/developers-guide-to-arweave/) tutorial on arweave, and I can confirm arlocal is running. When I try to create a transaction, the console reads 
```Error: Error signing transaction: Error: Unable to upload transaction: 400, unknown
    at Object.sign (injected.ts:266:13)
    at async Transactions.sign (transactions.ts:208:1)
    at async createTransaction (App.js:19:1)
```

The line of code that throws the error is `let transaction = await arweave.createTransaction({ data: formData })`
 
Running node v16.15.1 and npm 8.11.0.

**Comment by hlolli** [comment]
please submit javascript related issues to this repository https://github.com/ArweaveTeam/arweave-js
and if possible, include the full stacktrace in your ticket
