### ISSUE TITLE
Graphql limited to 100 responses?

### ISSUE THREAD

**Issue by ndrewtl** [ArweaveTeam/arweave#377]
I have been running a variant of the query exposed in the [Public Square](https://public-square.arweave.dev/) demo app, namely:
```
{
    transactions(first: 160, 
      tags: [
        {
          name: "App-Name",
          values: ["PublicSquare"]
        },
        {
          name: "Content-Type",
          values: ["text/plain"]
        },

      ]
    ) {
      edges {
        node {
          id
          data {
            size
          }
          tags {
            name,
            value
          }
        }
      }
    }
  }
```

However, no matter the number of results I specify, if it is above 100, I always receive a response of exactly 100 transactions. Is there an implicit limit on the number of results returned? And if so, is there any way to get around it?

**Comment by rosmcmahon** [comment]
this isn't really the forum to discuss GQL, but i'll just briefly mention that the max results _per page_ is 100. you need to paginate to get the rest of the result set [https://gql-guide.vercel.app/#pagination](https://gql-guide.vercel.app/#pagination)

...and the best place for this discussion is the [Arweave Dev discord](https://discord.gg/7ZPuxrpQq7)! hope to chat to you there soon! 😃
