### ISSUE TITLE
Crash: window is not defined

### ISSUE THREAD

**Issue by Jack-Works** [ArweaveTeam/arweave#379]
![image](https://user-images.githubusercontent.com/5390719/180968356-c1b8c1be-728c-4441-b3f6-fa29d319c979.png)

We're running it in a Web Worker and it crashes.

**Comment by rosmcmahon** [comment]
you were probably meaning to open this issue in the arweave-js github repo. however, the best place to discuss this is the [Arweave Dev](https://discord.gg/7ZPuxrpQq7) discord server

**Comment by Jack-Works** [comment]
Is this fixed?

**Comment by rosmcmahon** [comment]
See my previous comment. It's not relevant to this repo. This is the arweave miner's repo.
