### ISSUE TITLE
the connection was lost

### ISSUE THREAD

**Issue by echoof** [ArweaveTeam/arweave#408]
<img width="606" alt="arweave" src="https://user-images.githubusercontent.com/54647766/222066579-af1d3dcf-799c-4313-bb79-fe67b7d17a38.png">
what caused it

**Comment by ldmberman** [comment]
Which release are you on?

**Comment by echoof** [comment]
> Which release are you on?

Arweave : 2.6
OS ： ubuntu 18.04

**Comment by echoof** [comment]
> Which release are you on?

I refer to this tutorial for deployment. I don't know whether this is a successful operation or whether to start mining
https://docs.arweave.org/info/mining/mining-guide

**Comment by ldmberman** [comment]
It's safe to ignore these messages. Also, consider upgrading to [2.6.2](https://github.com/ArweaveTeam/arweave/releases/tag/N.2.6.2) - you won't see these warnings in the console there.
