### ISSUE TITLE
arweavenet data unavailable

### ISSUE THREAD

**Issue by Dreamerryao** [ArweaveTeam/arweave#418]
When I accessed this asset on the Solana blockchain (https://solscan.io/address/HqYJuoNgGCqkxfC2o8t5AMdohikYzrezMeniSa2RjBnL), I noticed that the Arweave links within it (https://arweave.net/fdAGozNqYIwjzV0igyv9gK10L-0NS_Xet4JZ00XirZ8) were not available. 

If you have knowledge about NFTs, you should know that the metadata information should be stored within. I was able to find the metadata information in the cache on OpenSea (https://opensea.io/assets/solana/HqYJuoNgGCqkxfC2o8t5AMdohikYzrezMeniSa2RjBnL). 

Therefore, the data must have existed for a period of time and then became unavailable, which raises questions about Arweave's claim of permanent storage.

**Comment by ldmberman** [comment]
Hi @Dreamerryao, the transaction does not [exist on Arweave](https://arweave.net/tx/fdAGozNqYIwjzV0igyv9gK10L-0NS_Xet4JZ00XirZ8/status). It appears, there was a relatively long fork at the time where this transaction belonged, and it was not re-included into the winning fork. Although reorgs deeper than 2 blocks are very rare, I would suggest you reach out to the project devs and suggest they increase the minimum number of confirmations to wait for.

**Comment by Dreamerryao** [comment]
tks for ur prompt reply! However, what I don't understand is why OpenSea can access the metadata, which means that the data was available for a period of time. According to what you said, has the forking length become too long?

**Comment by Dreamerryao** [comment]
Also, I don't think you can use this method to find the status of a transaction. For example (dnnUO6BzDP3AE2FMyjco69c8_tC1uoEcHQz2VPv2GyE) I can access it normally (https://arweave.net/dnnUO6BzDP3AE2FMyjco69c8_tC1uoEcHQz2VPv2GyE), but I cannot get its status (https://arweave.net/tx/dnnUO6BzDP3AE2FMyjco69c8_tC1uoEcHQz2VPv2GyE/status). @ldmberman

**Comment by Dreamerryao** [comment]
Therefore, based on my current understanding of Arweave, it is because no one has accessed this data for too long (about 6 months), causing the score for this data to be negligible and no miner willing to store them, resulting in the data being unavailable. However, this goes against the promoted philosophy of permanent storage.

**Comment by ldmberman** [comment]
No, this is not about storing data, this is about "committing" the transaction on the chain, similarly to how it works in any other chain.

`dnnUO6BzDP3AE2FMyjco69c8_tC1uoEcHQz2VPv2GyE` does not exist on Arweave either as the status endpoint [suggests](https://arweave.net/tx/dnnUO6BzDP3AE2FMyjco69c8_tC1uoEcHQz2VPv2GyE/status). In other words, it is not included in any of the block of the longest fork.

A potentially misleading behaviour here is `arweave.net/[txid]` not filtering the orphaned transactions out. The endpoint keeps serving the contents once it caches them. This is convenient as it serves the contents of pending transactions. However it becomes misleading if the transaction is orphaned. I will talk to the team to see if we can improve the caching behaviour of our gateway.

Nevertheless, `https://arweave.net/tx/[txid]/status` is the endpoint to watch for Arweave confirmations.

**Comment by Dreamerryao** [comment]
seems like all these 3000+ tx "not found".I don't think this is normal behavior.
(https://github.com/Dreamerryao/sol-metadata-parser/blob/main/output.json)

**Comment by Dreamerryao** [comment]
<img width="830" alt="截屏2023-05-01 16 53 21" src="https://user-images.githubusercontent.com/49583235/235431470-52641da8-615d-422f-acda-36bbdff87138.png">

**Comment by ldmberman** [comment]
@Dreamerryao apologies, I went into the totally wrong direction here. @rosmcmahon has pointed out `fdAGozNqYIwjzV0igyv9gK10L-0NS_Xet4JZ00XirZ8` is a "data item" - one of the many items "bundled" together by Bundlr and submitted in a single large L1 transaction (in this case `9_Z8vOZsxqkwU32_O4iKBmhVLqTC5afVcYe3VCyivK8`, and it's [confirmed](https://arweave.net/tx/9_Z8vOZsxqkwU32_O4iKBmhVLqTC5afVcYe3VCyivK8/status). Let's start from the beginning, what is the issue you are observing? I can see https://pxianiztnjqiyi6nlurigk75qcwxil7nbvf7lxvxqjm5grpcvwpq.arweave.net/fdAGozNqYIwjzV0igyv9gK10L-0NS_Xet4JZ00XirZ8 is actually serving the metadata.

**Comment by ldmberman** [comment]
You may use Viewblock to inspect data items - https://viewblock.io/arweave/tx/dnnUO6BzDP3AE2FMyjco69c8_tC1uoEcHQz2VPv2GyE.

**Comment by Dreamerryao** [comment]
Oh, I can access it now too, but from yesterday until just now when I checked, it was unavailable, indicating that this data item was unavailable for some time, but now it's available.

**Comment by rosmcmahon** [comment]
hi guys 👋 

dataItems like these are actually not visible to the protocol (miners). they are bundled by a bundling service, and unbundled and served by a gateway, like arweave.net. you can think of this as something like L2 txs, but that's not 100% accurate.

so in this case it may have been an intermittent issue on the arweave.net gateway that you were experiencing. this is actually managed by ARio, you can join their support server here => https://discord.gg/yxPdyEzvjq
