### ISSUE TITLE
./bin/start init    got error

### ISSUE THREAD

**Issue by ahhxfeng** [ArweaveTeam/arweave#442]
2023-07-06T18:24:34.852009+08:00 [error] : Error in process <0.9.0> on node 'arweave@127.0.0.1' with exit value:, {{badmatch,{error,{arweave,{{shutdown,{failed_to_start_child,ar_node_sup,{shutdown,{failed_to_start_child,ar_node_worker,{{case_clause,{[{block,<<>>,{<<"~">>,nil,nil}},no_hash,no_prefix,no_value},size => 1,<<"~">> => {root,{0,nil},no_hash,,<<>>},undefined,<<>>,undefined,0,0,undefined,[],0,1,0,1,0,undefined,0}],true}},[{ar_node_worker,init,1,[{file,"/home/think/work/Ar/arweave/apps/arweave/src/ar_node_worker.erl"},{line,97}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,390}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}}}}},{ar,start,[normal,[]]}}}}},[{ar,start,1,[{file,"/home/think/work/Ar/arweave/apps/arweave/src/ar.erl"},{line,592}]},{init,start_em,1,[]},{init,do_boot,3,[]}]}

**Comment by ahhxfeng** [comment]
platform : wsl2 ubuntu 22.04
code : git clone --recursive https://github.com/ArweaveTeam/arweave.git
erlang : Eshell V12.2.1  (abort with ^G)

**Comment by ahhxfeng** [comment]
I m try to build a local testnet arweave service for more clearly understand arweave, and when I use the `/bin/start init config_file config.json` i always got the error  

{"init terminating in do_boot",{{badmatch,{error,{arweave,{{shutdown,{failed_to_start_child,ar_node_sup,{shutdown,{failed_to_start_child,ar_node_worker,{{case_clause,false}

**Comment by ahhxfeng** [comment]
Does the arweave init has the hardware requirements ?

**Comment by rosmcmahon** [comment]
> I m try to build a local testnet arweave service for more clearly understand arweave, and when I use the `/bin/start init config_file config.json` i always got this error
> 
> {"init terminating in do_boot",{{badmatch,{error,{arweave,{{shutdown,{failed_to_start_child,ar_node_sup,{shutdown,{failed_to_start_child,ar_node_worker,{{case_clause,false}

Could you share your `config.json` also please?

**Comment by ahhxfeng** [comment]
Ok, `
{
        "mine": true,
        "init": true,
        "port": 1984,
        "data_dir": "~/arweave-testnet",
        "mining_addr": "zlq3iT61M4IGBIdx7EYAChLr79HLdsU4KlzfZmA8Yfw"
}
`

**Comment by rosmcmahon** [comment]
CC @ldmberman @JamesPiechota

**Comment by ahhxfeng** [comment]
thx, bro. let my try

**Comment by ahhxfeng** [comment]
I have make the change ` no_auto_join: true` in my config.json .But nothing seems change ,i still got the same error ,when i use` /bin/start init config_file config.json `

**Comment by ahhxfeng** [comment]
what is the right step of build a local testnet service ? is like this ?

1. > one node `./bin/start init `
2. > then other node `./bin/start peer ip`  ip is the init node ip ?

**Comment by JamesPiechota** [comment]
That error might be due to no storage modules. Try specifying one storage module and configuring the data_dir. You can check the mining guide for more info on those flags. 

Also since this is a new weave you won't have any data to sync.

**Comment by ahhxfeng** [comment]
Hello， @JamesPiechota 
This time i m not got error,when i add disk place to server.
But the process seem stoped, 

- Terminal display stop at (the process of arweave not exit ) :
- `Setting the packing chunk cache size limit to 1300 chunks.
   Setting the data chunk cache size limit to 1100 chunks`

- Log of arweave@127.0.0.1,1 display stop at:
- `2023-07-14T10:30:40.525868+00:00 [info] ar_arql_db:init/0:165 ar_arql_db: init, data_dir: /home/think/tmp/data
2023-07-14T10:30:45.944921+00:00 [info] ar_header_sync:init/0:61 event: ar_header_sync_start
2023-07-14T10:30:46.165168+00:00 [info] ar_data_sync:init/1:476 event: ar_data_sync_start, store_id: default
2023-07-14T10:30:49.825328+00:00 [info] ar_blacklist_middleware:start/0:33 event: ar_blacklist_middleware_start`

i have been waiting for a while（about 1 hours）, should i still wait ? The situaction is in right flow ？

**Comment by JamesPiechota** [comment]
No output is not necessarily a problem. You can try posting transactions and using the HTTP API

**Comment by ahhxfeng** [comment]
Hi @JamesPiechota ,
Does the gennis_block auto gennerate when init a weave ? or should i create manually? what should gennis_block like?

Cause when i start another node and try to join. i found the `block` dir is empty, and i will got the error
`failed to fetch the block index of any peers retry`

**Comment by ldmberman** [comment]
Running a new weave in the non-test mode has been broken for a while. We may fix it soon though ([a PR](https://github.com/ArweaveTeam/arweave/pull/447)).

In the meantime, you may join [the public testnet](https://github.com/ArweaveTeam/arweave#testnet) or try a test console (`./bin/shell`). For example, to start a node and make it mine a block in the test console:

```sh
ar_test_node:start().
ar_node:mine().
```
The test node is using the default port 1984.

**Comment by ldmberman** [comment]
@ahhxfeng the update is in the latest master; please, read the new [README section](https://github.com/ArweaveTeam/arweave#starting-new-weave) for instructions on how to start a local weave.

**Comment by ahhxfeng** [comment]
thx, bro
