### ISSUE TITLE
Genesis block TXs are not served

### ISSUE THREAD

**Issue by djwhitt** [ArweaveTeam/arweave#455]
It appears that TXs in the genesis block are no longer being served. While not a huge issue, this is visible when trying to index the chain from genesis (e.g. using an ar.io node).

**Comment by JamesPiechota** [comment]
Hey, genesis transactions are handled special and it looks like that handling broke several months back.

Genesis transactions are snapshotted as .json files in the repo here: https://github.com/ArweaveTeam/arweave/tree/master/data/genesis_txs

They *should* be copied into `data_dir/txs`, but that copy isn't happening anymore.

As a temporary workaround you can manually copy the genesis transaction json files from the [repo snapshot](https://github.com/ArweaveTeam/arweave/tree/master/data/genesis_txs) into your configured `data_dir` `txs` repo.

Once you do that they should be correctly served. I'll aim to put a fix into the next release.
