### ISSUE TITLE
How to get Data Stored of Arweave

### ISSUE THREAD

**Issue by stayForward09** [ArweaveTeam/arweave#520]
Hi,
How are you?
I'm Davee from [ev3.xyz](http://ev3.xyz/) team, and we are going to add key metric- Data Stored of Arweave to our site https://depin.ninja/, especialyy, Data stored of Arweave like as https://viewblock.io/arweave/stat/cumulativeWeaveSize, 
So I tried to access [api.viewblock.io/graphql](http://api.viewblock.io/graphql), but I can't find where I should get API_KEY and query docs.
Would you please help me to get relevant api and api documentation?
Thanks.

**Comment by samcamwilliams** [comment]
Hey Davee!

No need for an API key, unless you want to get the data at extremely high frequency. Assuming a normal access pattern, you could just grab this from the headers of the current block from any Arweave gateway/node. Arweave.net is a big open one that is reliable (live for >5 years). g8way.io is also becoming popular but you can check out the full list on [Viewblock](https://viewblock.io/arweave/gateways) for more options!

The route you need is `GET /block/current`, which will return a JSON encoding of the block. The field you want from the block is `weave_size`. Only thing to watch out for is that the JSON block encoding is relatively large (~300 KB or so).

Example with cURL:
```
sam@* ~ % curl https://arweave.net/block/current | jq .weave_size
"164241648689398"
```

Result is encoded as a BigNum string in preparation for it to increase 🫡.

Happy integrating!
Sam

**Comment by stayForward09** [comment]
Thanks for your kind help @samcamwilliams 
I can get correct data from https://arweave.net/block/current, but the response is a bit large as you said.
But I can't run this command; 
`sam@* ~ % curl https://arweave.net/block/current | jq .weave_size`
Would you help me once more?
Thanks.

**Comment by vird** [comment]
I guess without prefix `curl https://arweave.net/block/current | jq .weave_size`
