### ISSUE TITLE
ARweave decentralised gateway

### ISSUE THREAD

**Issue by maxmetagravity** [ArweaveTeam/arweave#603]
I have test AR.IO gateway in official configuration：

#docker-compose up -d
Creating network "ar-io-network" with the default driver
Creating ariod1node4_observer_1 ... done
Creating ariod1node4_resolver_1 ... done
Creating ariod1node4_redis_1 ... done
Creating ariod1node4_core_1 ... done
Creating ariod1node4_envoy_1 ... done

#docker-compose ps
Name Command State Ports
ariod1node4_core_1 /bin/sh docker-entrypoint.sh Up (healthy) | 0.0.0.0:4000->4000/tcp,:::4000->4000/tcp
ariod1node4_envoy_1 /docker-entrypoint.sh envo ... Up | 10000/tcp, 0.0.0.0:3000->3000/tcp,:::3000->3000/tcp
ariod1node4_observer_1 /nodejs/bin/node ./dist/se ... Up (healthy) | 0.0.0.0:5050->5050/tcp,:::5050->5050/tcp
ariod1node4_redis_1 docker-entrypoint.sh redis ... Up | 0.0.0.0:32779->6379/tcp,:::32779->6379/tcp
ariod1node4_resolver_1 /nodejs/bin/node ./dist/se ... Exit | 0

when ARIO is running and sync to HEIGHT 1289xx，

#curl http://localhost:3000/info //We can get the arweave node info

#curl http://localhost:4000/ar-io/info //We can get the ario gw info

#curl http://localhost:4000/info // We get a 404 error and Cant find /info，

and after try all arweave API on port 4000，not find any api works ，all api endpoint responed 404 error

Through the above test, we can confirm that on the core service of ARIO, when the request needs to be proxied to a trusted gateway such as arweave.net through envoy under normal circumstances, the service is provided by the API of arweave.net. Direct access to Arweave API endpoints such as /info of the core service will return a 404 error.

This shows that the ario core service does not provide these HTTP API endpoints, but relies on the backend trusted gateway (such as arweave.net) to handle these requests.

I thought ario provided similar functions to arweave.net, so I am a little confused now. What services can ARIO's core provide that can be directly experienced? ? (except ARNS 、Observer、Bundler Services ? ? )

Based on the above test, another question is : If arweave.net is down, does that mean the AR.IO network is not functioning properly?

Maybe I don't know enough about ario, but I still want to know if there are some good open source gateways in the arweave ecosystem that can work independently (not just as a proxy) and are compatible with the HTTP API of arweave.net

**Comment by JamesPiechota** [comment]
Hi, this repo is for the core reference miner. For questions about any of the ARIO projects I'd recommend checking out their [discord](https://discord.com/invite/7zUPfN4D6g) or one of their [github repos](https://github.com/ar-io)

**Comment by maxmetagravity** [comment]
Ok, this question is not about ario, I'm looking for more general advice on arweave gateways

**Comment by JamesPiechota** [comment]
This repo doesn't really have any gateway functionality in it. Typically a gateway might run backing nodes, but the gateway itself is run off a different codebase. You're welcome to keep the question open, maybe someone will chime in. But if you have gateway questions I think you'd be better off asking them on a gateway repo or forum.
