### ISSUE TITLE
The wallet balance reached almost 10^15 AR. 

### ISSUE THREAD

**Issue by techinged** [ArweaveTeam/arweave#604]
I met another problem when I deployed a private arweave network. I used the script as below to launch arweave network. 
`bin/start init data_dir /opt/arweave/newtest/data/ mining_addr g842KgJcA1_I_m4fcZsk_2OSBbEL8PGzpbfdsmuy5MQ storage_module 0,g842KgJcA1_I_m4fcZsk_2OSBbEL8PGzpbfdsmuy5MQ mine`
In the beginnig, the wallet balance of `g842KgJcA1_I_m4fcZsk_2OSBbEL8PGzpbfdsmuy5MQ` is 10^12 AR. When I uploaded a file with this wallet, the wallet balance reached almost 10^15 AR. The wallet balance was increased by 1000 times. Is it normal? Is it not a bug?

**Comment by techinged** [comment]
@vird 
Hi, Can you have a look at this issue? Thanks a lot.

**Comment by vird** [comment]
price per GB grows if hashrate is low. In testnet price per transaction can be 10000 AR easily for 1 chunk. Even more

**Comment by techinged** [comment]
> price per GB grows if hashrate is low. In testnet price per transaction can be 10000 AR easily for 1 chunk. Even more
@vird 
Is there any way that limits the price to a certain numerical value for 1 chunk?

**Comment by vird** [comment]
No. At least I don't know

**Comment by techinged** [comment]
@vird 
Ok, thank you.
