### ISSUE TITLE
Block should contain the time that the block was mined.

### ISSUE THREAD

**Issue by codybartfast** [ArweaveTeam/arweave#66]
The AR block contains a 'timestamp' member, but it appears to be the time that mining started not the time that mining succeeded.

The Timestamp value returned by [server](https://github.com/ArweaveTeam/arweave/blob/7cf5c0cfeec19f8ec4455b14de932fcc9b51f9e9/src/ar_mine.erl#L183) in ar_mine appears to be the Timestamp evaluated [before](https://github.com/ArweaveTeam/arweave/blob/7cf5c0cfeec19f8ec4455b14de932fcc9b51f9e9/src/ar_mine.erl#L34) the server was spawned.  This is then the valued used when ar_weave:add is called in [ar_node](https://github.com/ArweaveTeam/arweave/blob/a159cbc89c929305c38391e320b32b7d0687b0a8/src/ar_node.erl#L1514).

Whether this is intentional or not, I think the block should contain the time it was mined, as an additional member if necessary.

If the existing member were modified to show the mined time then, that timestamp should probably still be strictly monotonic increasing during migration - to avoid zero or negative durations.  I think it would be so long as any clock variation between mines is less than the time it takes for a new block to propagate.  But we would see some timestamps differing by just a few seconds and others differing by the time taken to mine the two previous blocks.

**Comment by samcamwilliams** [comment]
Thanks, @codybartfast ! We have been working on some similar issues in our private Arweave repo. I will add this to that set.

All the best,
Sam

**Comment by ldmberman** [comment]
We properly account for the time spent mining starting from N.1.6.3.0, closing this.
