### ISSUE TITLE
how can I compile the version 2.9.0，I got an error

### ISSUE THREAD

**Issue by xgocn** [ArweaveTeam/arweave#666]
the source code I used with is https://github.com/ArweaveTeam/arweave/archive/refs/tags/N.2.9.0-early-adopter.tar.gz
`./rebar3 as hisweave tar
===> verifying dependencies...
CMake Error: The source directory"/root/arweave2.9/apps/arweave/lib/RandomX" does not appear to contain
CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
oo> Hook for compile failed!
`

I had tried `git clone --recursive https://github.com/ArweaveTeam/arweave.git` got 2.8.3

**Comment by vird** [comment]
```
git checkout release/N.2.9.0-early-adopter
git submodule update
```

**Comment by xgocn** [comment]
ok，thx！

**Comment by xgocn** [comment]
when I  compile the source in different ubuntu 22.04 system,I got these errors
`
===> Analyzing applications...
===> Compiling arweave
apps/arweave/src/ar_bench_2_9.erl:45:31: Warning: variable 'Tail' is unused

apps/arweave/src/ar_mining_worker.erl:314:1: Warning: this clause for process_all_sub_chunks/5 cannot match because a previous clause at line 309 always matches

apps/arweave/src/ar_replica_2_9.erl:262:29: Warning: this clause cannot match because its guard evaluates to 'false'
apps/arweave/src/ar_replica_2_9.erl:263:31: Warning: this clause cannot match because its guard evaluates to 'false'
apps/arweave/src/ar_replica_2_9.erl:271:21: Warning: this clause cannot match because its guard evaluates to 'false'
apps/arweave/src/ar_replica_2_9.erl:365:29: Warning: this clause cannot match because its guard evaluates to 'false'
apps/arweave/src/ar_replica_2_9.erl:366:31: Warning: this clause cannot match because its guard evaluates to 'false'

apps/arweave/src/ar_mine_randomx.erl:135:1: Warning: function write_scratchpad_to_disk/3 is unused

apps/arweave/src/ar_doctor_bench.erl:165:1: Warning: function random_chunk_pread/2 is unused
apps/arweave/src/ar_doctor_bench.erl:167:1: Warning: function random_chunk_pread/5 is unused
apps/arweave/src/ar_doctor_bench.erl:178:1: Warning: function random_dev_pread/2 is unused
apps/arweave/src/ar_doctor_bench.erl:180:1: Warning: function random_dev_pread/5 is unused
apps/arweave/src/ar_doctor_bench.erl:194:1: Warning: function dd_chunk_files_read/2 is unused
apps/arweave/src/ar_doctor_bench.erl:196:1: Warning: function dd_chunk_files_read/5 is unused
apps/arweave/src/ar_doctor_bench.erl:207:1: Warning: function dd_chunk_file_read/2 is unused
apps/arweave/src/ar_doctor_bench.erl:209:1: Warning: function dd_chunk_file_read/5 is unused
apps/arweave/src/ar_doctor_bench.erl:222:1: Warning: function dd_dev_file_read/2 is unused
apps/arweave/src/ar_doctor_bench.erl:224:1: Warning: function dd_dev_file_read/5 is unused
apps/arweave/src/ar_doctor_bench.erl:236:1: Warning: function dd_devs_read/2 is unused
apps/arweave/src/ar_doctor_bench.erl:238:1: Warning: function dd_devs_read/5 is unused
apps/arweave/src/ar_doctor_bench.erl:251:1: Warning: function dd_dev_read/2 is unused
apps/arweave/src/ar_doctor_bench.erl:253:1: Warning: function dd_dev_read/5 is unused
apps/arweave/src/ar_doctor_bench.erl:266:1: Warning: function get_mounted_device/1 is unused
apps/arweave/src/ar_doctor_bench.erl:271:1: Warning: function open_files/2 is unused
apps/arweave/src/ar_doctor_bench.erl:282:1: Warning: function pread/3 is unused
apps/arweave/src/ar_doctor_bench.erl:284:9: Warning: variable 'Filepath' is unused
apps/arweave/src/ar_doctor_bench.erl:290:1: Warning: function dd_files/3 is unused
apps/arweave/src/ar_doctor_bench.erl:296:1: Warning: function dd/4 is unused

===> Compiling apps/arweave/src/ar_chunk_storage.erl failed
apps/arweave/src/ar_chunk_storage.erl:968:45: syntax error before: ','

apps/arweave/src/ar_chunk_storage.erl:831:7: function store_entropy2/3 undefined

apps/arweave/src/ar_chunk_storage.erl:770:1: Warning: function update_replica_2_9_entropy_record/2 is unused

`

**Comment by vird** [comment]
`git status`
Are you sure that you not modified any file?
`git log`
Which commit do you use?

**Comment by xgocn** [comment]
git clone --recursive https://github.com/ArweaveTeam/arweave.git
cd arweave
git checkout release/N.2.9.0-early-adopter
git submodule update
.rebar as prod tar

**Comment by xgocn** [comment]
I did not modify any files

**Comment by xgocn** [comment]
```
root@youshu:~# sudo apt list --installed | grep -E 'gcc|g\+\+|erlang|libssl-dev|libgmp-dev|libsqlite3-dev|make|cmake'

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

automake/jammy,now 1:1.16.5-1.3 all [installed]
cmake-data/jammy-updates,now 3.22.1-1ubuntu1.22.04.2 all [installed,automatic]
cmake/jammy-updates,now 3.22.1-1ubuntu1.22.04.2 amd64 [installed]
erlang-mode/unknown,now 1:25.0.4-1 all [installed,automatic]
erlang-solutions/now 2.0 all [installed,local]
esl-erlang/unknown,now 1:25.3-1 amd64 [installed]
g++-11/jammy-updates,jammy-security,now 11.4.0-1ubuntu1~22.04 amd64 [installed,automatic]
g++/jammy,now 4:11.2.0-1ubuntu1 amd64 [installed]
gcc-11-base/jammy-updates,jammy-security,now 11.4.0-1ubuntu1~22.04 amd64 [installed,automatic]
gcc-11/jammy-updates,jammy-security,now 11.4.0-1ubuntu1~22.04 amd64 [installed,automatic]
gcc-12-base/jammy-updates,jammy-security,now 12.3.0-1ubuntu1~22.04 amd64 [installed,automatic]
gcc/jammy,now 4:11.2.0-1ubuntu1 amd64 [installed]
libgcc-11-dev/jammy-updates,jammy-security,now 11.4.0-1ubuntu1~22.04 amd64 [installed,automatic]
libgcc-s1/jammy-updates,jammy-security,now 12.3.0-1ubuntu1~22.04 amd64 [installed,automatic]
libgmp-dev/jammy,now 2:6.2.1+dfsg-3ubuntu1 amd64 [installed]
libsqlite3-dev/jammy-updates,jammy-security,now 3.37.2-2ubuntu0.3 amd64 [installed]
libssl-dev/jammy-updates,jammy-security,now 3.0.2-0ubuntu1.18 amd64 [installed]
make/jammy,now 4.3-4.1build1 amd64 [installed]
makedumpfile/jammy-updates,now 1:1.7.0-1ubuntu0.1 amd64 [installed,automatic]
```

**Comment by vird** [comment]
Try this one https://github.com/ArweaveTeam/arweave/tree/fix/syntax
I'll merge it a bit later

**Comment by xgocn** [comment]
Thank U！
