### ISSUE TITLE
Mining config generator needs styling

### ISSUE THREAD

**Issue by samcamwilliams** [ArweaveTeam/arweave#67]
The Arweave mining configuration generator (found here: https://github.com/ArweaveTeam/arweave/blob/feature/config-generator/src/apps/config_generator.html ) is helpful, but is currently poorly styled.

There is up to a 200 AR bounty available for anyone that would like to give this a nicer UI!

**Comment by cedriking** [comment]
@mkg20001 200 AR have been sent!
Transaction ID: `HzFb4ebmv-hpt-7tQhgNChWwHmqdRvuApJsJ3w_doTw`

Thank you!
