### ISSUE TITLE
Mining config generator should elegantly handle missing data

### ISSUE THREAD

**Issue by samcamwilliams** [ArweaveTeam/arweave#68]
The mining config generator web page ( https://github.com/ArweaveTeam/arweave/blob/feature/config-generator/src/apps/config_generator.html ) currently does not handle missing input very well.

For example, if you do not provide a trusted peer, the output command will include `./arweave-server peer mining_addr` which is not a valid argument set.

100 AR for anyone that can add the appropriate error state handling!

**Comment by ldmberman** [comment]
Addressed by https://github.com/ArweaveTeam/arweave/pull/171.

**Comment by cedriking** [comment]
@mkg20001 100 AR sent!
Transaction ID: `oXSHOjIIcos-8wc9Sv5d1Y2Jhfaiqi0Cp3tjkWRXjwo`

Thank you!
