### ISSUE TITLE
Timezone mismatch in arweave-server log

### ISSUE THREAD

**Issue by batzor** [ArweaveTeam/arweave#73]
arweave-server uses erlang.system_time() to show its log. I think os.system_time() is more appropriate to use in this case.

**Comment by samcamwilliams** [comment]
Hi @qvntm , thanks for the report.

Do you mean timestamp that is emitted on the Erlang console, or the `make log` console?

**Comment by codybartfast** [comment]
Hi, I don't know Erlang but I found [this post](https://github.com/bitwalker/timex/issues/134) suggesting erlang: has the advantage of having monotonic time.   Fwi, my preferences for log time are; 1) monotonic, 2) UTC (or  angels will cry), 3) Sortable format (i.e., one of the [ISO 8061](https://en.wikipedia.org/wiki/ISO_8601) formats)

**Comment by qvntm** [comment]
@samcamwilliams erlang console.

**Comment by ldmberman** [comment]
The only timestamped console messages now should be level=error messages from logger, which uses os:system_time.
