### ISSUE TITLE
Harmonise use of bignum strings across TX and block JSON.

### ISSUE THREAD

**Issue by samcamwilliams** [ArweaveTeam/arweave#74]
At the moment TXs use strings to represent (potentially) very large numbers, keeping compatibility with 32 bit programming environments. Block JSON representations do not follow the same standard and should be converted.

**Comment by ldmberman** [comment]
The fields that are already or potentially very large has been converted in [the latest release](https://github.com/ArweaveTeam/arweave/releases/tag/N.2.4.0.0).
