### ISSUE TITLE
Prefer Rebar3 to makefile

### ISSUE THREAD

**Issue by enilsen16** [ArweaveTeam/arweave#9]
I've noticed a few things that I think rebar3 could help solve.

- No built tarbars of the testnet, this would be pretty easy to do with rebar3 and then you could just drop the tarball and your keys on a server.

- Manually bring in dependencies. I noticed the current dependencies are actually source code. Pulling these from hex would make updating/removing etc much easier.

What do you think?

**Comment by allquantor** [comment]
here is docker file we made
https://github.com/toknapp/arweave-1/blob/01c8ef1b7917ae3a8eb94de562f2576893555c9f/Dockerfile
