### ISSUE TITLE
GET /block/Type/ID errors messages are switched 

### ISSUE THREAD

**Issue by llaisdy** [ArweaveTeam/arweave#96]
Request with invalid hash returns "invalid height";
Request with invalid height returns "invalid hash".

See

https://github.com/ArweaveTeam/arweave/blob/master/src/ar_http_iface.erl#L476-L480

**Comment by lhendre** [comment]
Hey, wanted to potentially contribute to arweave, and looking through whats available, this one seemed a decent starter but its old and wouldnt be surprised if the fix is in another branch already

**Comment by ldmberman** [comment]
This one has been fixed a while ago.
