### ISSUE TITLE
GET /wallet/Address/last_tx should have a node unavailable clause

### ISSUE THREAD

**Issue by llaisdy** [ArweaveTeam/arweave#97]
... like the one in `GET /wallet/Address/balance`.

See

https://github.com/ArweaveTeam/arweave/blob/master/src/ar_http_iface.erl#L409-L435

**Comment by llaisdy** [comment]
Ditto `GET /hash_list` & `GET /wallet_list`.

**Comment by ldmberman** [comment]
Fixed in one of the latest releases.
