### ISSUE TITLE
GET /price/SizeInBytes[/Addr] should catch non-integer SizeInBytes

### ISSUE THREAD

**Issue by llaisdy** [ArweaveTeam/arweave#98]
Both endpoints currently return 500.  eg http://167.99.249.43:1984/price/121x23/qweasd

See

https://github.com/ArweaveTeam/arweave/blob/master/src/ar_http_iface.erl#L325-L343

**Comment by istride** [comment]
I'm new to Erlang and Arweave and this looks like a good first issue to tackle, however, as it is a fairly old issue, I wonder whether it is still relevant. At the very least, I can see that the bug still exists.

My suggestion is for these endpoints to return a 400 error code and an error message as simple text, such as "Size in bytes should be an integer". Is that what we're looking for here?

**Comment by ldmberman** [comment]
Hi @istride, yep, the issue is still relevant. However, there is a fix already in a branch that is not pushed yet.
